// generated by make_cmds.py, do not edit this file!
// do not include this file in your .c file, should only be included by test_types.h!

#define CMD_ECHO 0
#define CMD_GET_SERVER_VERSION 1
#define CMD_SHARE_MEMSET 2
#define CMD_SHARE_MEMCPY 3
#define CMD_READ_MEMORY 4
#define CMD_WRITE_MEMORY 5
#define CMD_GET_WORD 6
#define CMD_SET_WORD 7
#define CMD_SET_WORD_AND_WAIT 8
#define CMD_HOSTAPI_INIT_LIB 9
#define CMD_HOSTAPI_INIT_CTX 10
#define CMD_HOSTAPI_BL_GET_CHALLENGE 11
#define CMD_HOSTAPI_BL_DEBUG_AUTH 12
#define CMD_HOSTAPI_BL_VERIFY_IMAGE 13
#define CMD_HOSTAPI_BL_VERIFY_IMAGE_DISCRETE 14
#define CMD_HOSTAPI_BL_UPGRADE_FW_IMAGE 15
#define CMD_HOSTAPI_BL_CLOSE_DEBUG 16
#define CMD_HOSTAPI_BL_GET_VERSION 17
#define CMD_HOSTAPI_BL_INJECT_ERROR 18
#define CMD_HOSTAPI_BL_READ_OTP 19
#define CMD_HOSTAPI_BL_READ_REG 20
#define CMD_HOSTAPI_BL_SET_UART_BAUDRATE 21
#define CMD_HOSTAPI_BL_SET_HSM_FREQ 22
#define CMD_HOSTAPI_BL_WRITE_OTP 23
#define CMD_HOSTAPI_BL_WRITE_REG 24
#define CMD_HOSTAPI_BL_ENCRYPT_KEY 25
#define CMD_HOSTAPI_BL_FW_AUTH 26
#define CMD_HOSTAPI_BL_GET_RANDOM_KEY 27
#define CMD_HOSTAPI_BL_GET_SELF_TEST_RESULT 28
#define CMD_HOSTAPI_BL_GET_SOCID 29
#define CMD_HOSTAPI_BL_SELF_TEST 30
#define CMD_HOSTAPI_GET_VERSION 31
#define CMD_HOSTAPI_ECDSA_INIT 32
#define CMD_HOSTAPI_ECDSA_UPDATE 33
#define CMD_HOSTAPI_ECDSA_FINISH_GEN 34
#define CMD_HOSTAPI_ECDSA_FINISH_VERIFY 35
#define CMD_HOSTAPI_ECDSA_ONEPASS_GEN 36
#define CMD_HOSTAPI_ECDSA_ONEPASS_GEN_WITH_DIGEST 37
#define CMD_HOSTAPI_ECDSA_ONEPASS_VERIFY 38
#define CMD_HOSTAPI_ECDSA_ONEPASS_VERIFY_WITH_DIGEST 39
#define CMD_HOSTAPI_ECDSA_ONEPASS_EX 40
#define CMD_HOSTAPI_AEAD_INIT 41
#define CMD_HOSTAPI_AEAD_INIT_WITH_PLAIN_KEY 42
#define CMD_HOSTAPI_AEAD_UPDATE 43
#define CMD_HOSTAPI_AEAD_FINISH_DEC 44
#define CMD_HOSTAPI_AEAD_FINISH_ENC 45
#define CMD_HOSTAPI_AEAD_ONEPASS_ENC 46
#define CMD_HOSTAPI_AEAD_ONEPASS_ENC_WITH_PLAIN_KEY 47
#define CMD_HOSTAPI_AEAD_ONEPASS_DEC 48
#define CMD_HOSTAPI_AEAD_ONEPASS_DEC_WITH_PLAIN_KEY 49
#define CMD_HOSTAPI_CHACHA_INIT 50
#define CMD_HOSTAPI_CHACHA_INIT_WITH_PLAIN_KEY 51
#define CMD_HOSTAPI_CHACHA_UPDATE 52
#define CMD_HOSTAPI_CHACHA_FINISH_DEC 53
#define CMD_HOSTAPI_CHACHA_FINISH_ENC 54
#define CMD_HOSTAPI_CHACHA_ONEPASS_ENC 55
#define CMD_HOSTAPI_CHACHA_ONEPASS_ENC_WITH_PLAIN_KEY 56
#define CMD_HOSTAPI_CHACHA_ONEPASS_DEC 57
#define CMD_HOSTAPI_CHACHA_ONEPASS_DEC_WITH_PLAIN_KEY 58
#define CMD_HOSTAPI_CHANGE_CONTROL_FIELD 59
#define CMD_HOSTAPI_CHANGE_LIFECYCLE 60
#define CMD_HOSTAPI_CLOSE_DEBUG 61
#define CMD_HOSTAPI_CREATE_COUNTER 62
#define CMD_HOSTAPI_CTX_POLL 63
#define CMD_HOSTAPI_DEBUG_AUTH 64
#define CMD_HOSTAPI_DELETE_COUNTER 65
#define CMD_HOSTAPI_DRIVER_GET_VERSION 66
#define CMD_HOSTAPI_DRIVER_INIT_LIBRANY 67
#define CMD_HOSTAPI_ENTER_WFI 68
#define CMD_HOSTAPI_GEN_RANDOM 69
#define CMD_HOSTAPI_GET_CHALLENGE 70
#define CMD_HOSTAPI_GET_EMU_STATUS 71
#define CMD_HOSTAPI_GET_UTC_TIME 72
#define CMD_HOSTAPI_HASH_INIT 73
#define CMD_HOSTAPI_HASH_UPDATE 74
#define CMD_HOSTAPI_HASH_FINISH 75
#define CMD_HOSTAPI_HASH_ONEPASS 76
#define CMD_HOSTAPI_HMAC_INIT 77
#define CMD_HOSTAPI_HMAC_INIT_WITH_KEY 78
#define CMD_HOSTAPI_HMAC_UPDATE 79
#define CMD_HOSTAPI_HMAC_FINISH_GEN 80
#define CMD_HOSTAPI_HMAC_FINISH_VERIFY 81
#define CMD_HOSTAPI_HMAC_ONEPASS_GEN 82
#define CMD_HOSTAPI_HMAC_ONEPASS_GEN_WITH_KEY 83
#define CMD_HOSTAPI_HMAC_ONEPASS_VERIFY 84
#define CMD_HOSTAPI_HMAC_ONEPASS_VERIFY_WITH_KEY 85
#define CMD_HOSTAPI_INCREASE_COUNTER 86
#define CMD_HOSTAPI_INJECT_ERROR 87
#define CMD_HOSTAPI_INSTALL_ENCRYPTED_KEY 88
#define CMD_HOSTAPI_INSTALL_RANDOM_KEY 89
#define CMD_HOSTAPI_KM_GEN_KEY 90
#define CMD_HOSTAPI_KM_IMPORT_KEY 91
#define CMD_HOSTAPI_KM_DERIVE_KEY 92
#define CMD_HOSTAPI_KM_DERIVE_KEY_TO_SOC 93
#define CMD_HOSTAPI_KM_EXCHANGE_KEY 94
#define CMD_HOSTAPI_KM_EXPORT_KEY 95
#define CMD_HOSTAPI_KM_GET_PUB_FROM_PRIV 96
#define CMD_HOSTAPI_KM_REMOVE_KEY 97
#define CMD_HOSTAPI_KM_SM9_EXCHANGE_KEY 98
#define CMD_HOSTAPI_MAC_INIT 99
#define CMD_HOSTAPI_MAC_INIT_WITH_KEY 100
#define CMD_HOSTAPI_MAC_UPDATE 101
#define CMD_HOSTAPI_MAC_FINISH_GEN 102
#define CMD_HOSTAPI_MAC_FINISH_VERIFY 103
#define CMD_HOSTAPI_MAC_ONEPASS_GEN 104
#define CMD_HOSTAPI_MAC_ONEPASS_GEN_WITH_KEY 105
#define CMD_HOSTAPI_MAC_ONEPASS_VERIFY 106
#define CMD_HOSTAPI_MAC_ONEPASS_VERIFY_WITH_KEY 107
#define CMD_HOSTAPI_READ_COUNTER 108
#define CMD_HOSTAPI_READ_OTP 109
#define CMD_HOSTAPI_READ_REG 110
#define CMD_HOSTAPI_RSA_CIPHER 111
#define CMD_HOSTAPI_RSA_SIGN_INIT 112
#define CMD_HOSTAPI_RSA_SIGN_UPDATE 113
#define CMD_HOSTAPI_RSA_SIGN_FINISH_GEN 114
#define CMD_HOSTAPI_RSA_SIGN_FINISH_VERIFY 115
#define CMD_HOSTAPI_RSA_SIGN_ONEPASS_GEN 116
#define CMD_HOSTAPI_RSA_SIGN_ONEPASS_GEN_WITH_DIGEST 117
#define CMD_HOSTAPI_RSA_SIGN_ONEPASS_VERIFY 118
#define CMD_HOSTAPI_RSA_SIGN_ONEPASS_VERIFY_WITH_DIGEST 119
#define CMD_HOSTAPI_RSA_SIGN_ONEPASS_EX 120
#define CMD_HOSTAPI_SET_UART_BAUDRATE 121
#define CMD_HOSTAPI_SET_UTC_TIME 122
#define CMD_HOSTAPI_SM2_CIPHER 123
#define CMD_HOSTAPI_SM2_SIGN_INIT 124
#define CMD_HOSTAPI_SM2_SIGN_UPDATE 125
#define CMD_HOSTAPI_SM2_SIGN_FINISH_GEN 126
#define CMD_HOSTAPI_SM2_SIGN_FINISH_VERIFY 127
#define CMD_HOSTAPI_SM2_SIGN_ONEPASS_GEN 128
#define CMD_HOSTAPI_SM2_SIGN_ONEPASS_GEN_WITH_DIGEST 129
#define CMD_HOSTAPI_SM2_SIGN_ONEPASS_VERIFY 130
#define CMD_HOSTAPI_SM2_SIGN_ONEPASS_VERIFY_WITH_DIGEST 131
#define CMD_HOSTAPI_SM2_SIGN_ONEPASS_EX 132
#define CMD_HOSTAPI_SM9_CIPHER 133
#define CMD_HOSTAPI_SM9_SIGN_ONEPASS_GEN 134
#define CMD_HOSTAPI_SM9_SIGN_ONEPASS_VERIFY 135
#define CMD_HOSTAPI_SYMM_CIPHER_INIT 136
#define CMD_HOSTAPI_SYMM_CIPHER_INIT_WITH_PLAIN_KEY 137
#define CMD_HOSTAPI_SYMM_CIPHER_UPDATE 138
#define CMD_HOSTAPI_SYMM_CIPHER_FINISH 139
#define CMD_HOSTAPI_SYMM_CIPHER_ONEPASS 140
#define CMD_HOSTAPI_SYMM_CIPHER_ONEPASS_WITH_PLAIN_KEY 141
#define CMD_HOSTAPI_UPGRADE_FW_IMAGE 142
#define CMD_HOSTAPI_VERIFY_IMAGE 143
#define CMD_HOSTAPI_VERIFY_TBBR_IMG 144
#define CMD_HOSTAPI_WRITE_OTP 145
#define CMD_HOSTAPI_WRITE_REG 146
#define CMD_HOSTAPI_TEST_READ_MEMORY 147
#define CMD_HOSTAPI_TEST_WRITE_MEMORY 148
#define CMD_HOSTAPI_TEST_JUMP_TO_ADDR 149
#define CMD_HOSTAPI_TEST_JUMP_TO_LOOP 150
#define CMD_HOSTAPI_RSA_CIPHER_WITH_PLAIN_KEY 151
#define CMD_HOSTAPI_SM2_CIPHER_WITH_PLAIN_KEY 152
#define CMD_HOSTAPI_RSA_SIGN_INIT_WITH_PLAIN_KEY 153
#define CMD_HOSTAPI_SM2_SIGN_INIT_WITH_PLAIN_KEY 154
#define CMD_HOSTAPI_ECDSA_INIT_WITH_PLAIN_KEY 155
#define CMD_HOSTAPI_SM9_CIPHER_WITH_PLAIN_KEY 156
#define CMD_HOSTAPI_SM9_SIGN_ONEPASS_GEN_WITH_PLAIN_KEY 157
#define CMD_HOSTAPI_UPGRADE_FW_IMAGE_INIT 158
#define CMD_HOSTAPI_UPGRADE_FW_IMAGE_UPDATE 159
#define CMD_HOSTAPI_UPGRADE_FW_IMAGE_FINISH 160
#define CMD_HOSTAPI_PQC_DSA_ONEPASS_EX 161
#define CMD_HOSTAPI_PQC_ML_KEM_EX 162
#define CMD_MAX_COUNT 163

uint16_t test_cmd_echo(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_get_server_version(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_share_memset(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_share_memcpy(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_read_memory(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_write_memory(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_get_word(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_set_word(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_set_word_and_wait(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_init_lib(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_init_ctx(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_get_challenge(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_debug_auth(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_verify_image(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_verify_image_discrete(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_upgrade_fw_image(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_close_debug(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_get_version(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_inject_error(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_read_otp(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_read_reg(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_set_uart_baudrate(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_set_hsm_freq(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_write_otp(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_write_reg(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_encrypt_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_fw_auth(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_get_random_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_get_self_test_result(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_get_socid(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_bl_self_test(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_get_version(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_finish_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_finish_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_onepass_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_onepass_gen_with_digest(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_onepass_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_onepass_verify_with_digest(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_onepass_ex(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_init_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_finish_dec(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_finish_enc(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_onepass_enc(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_onepass_enc_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_onepass_dec(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_aead_onepass_dec_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_init_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_finish_dec(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_finish_enc(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_onepass_enc(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_onepass_enc_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_onepass_dec(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_chacha_onepass_dec_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_change_control_field(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_change_lifecycle(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_close_debug(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_create_counter(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ctx_poll(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_debug_auth(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_delete_counter(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_driver_get_version(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_driver_init_librany(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_enter_wfi(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_gen_random(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_get_challenge(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_get_emu_status(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_get_utc_time(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hash_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hash_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hash_finish(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hash_onepass(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_init_with_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_finish_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_finish_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_onepass_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_onepass_gen_with_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_onepass_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_hmac_onepass_verify_with_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_increase_counter(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_inject_error(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_install_encrypted_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_install_random_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_gen_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_import_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_derive_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_derive_key_to_soc(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_exchange_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_export_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_get_pub_from_priv(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_remove_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_km_sm9_exchange_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_init_with_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_finish_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_finish_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_onepass_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_onepass_gen_with_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_onepass_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_mac_onepass_verify_with_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_read_counter(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_read_otp(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_read_reg(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_cipher(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_finish_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_finish_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_onepass_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_onepass_gen_with_digest(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_onepass_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_onepass_verify_with_digest(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_onepass_ex(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_set_uart_baudrate(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_set_utc_time(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_cipher(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_finish_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_finish_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_onepass_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_onepass_gen_with_digest(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_onepass_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_onepass_verify_with_digest(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_onepass_ex(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm9_cipher(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm9_sign_onepass_gen(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm9_sign_onepass_verify(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_symm_cipher_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_symm_cipher_init_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_symm_cipher_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_symm_cipher_finish(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_symm_cipher_onepass(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_symm_cipher_onepass_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_upgrade_fw_image(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_verify_image(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_verify_tbbr_img(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_write_otp(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_write_reg(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_test_read_memory(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_test_write_memory(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_test_jump_to_addr(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_test_jump_to_loop(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_cipher_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_cipher_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_rsa_sign_init_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm2_sign_init_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_ecdsa_init_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm9_cipher_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_sm9_sign_onepass_gen_with_plain_key(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_upgrade_fw_image_init(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_upgrade_fw_image_update(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_upgrade_fw_image_finish(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_pqc_dsa_onepass_ex(const test_cmd_st *cmd, test_rsp_st *rsp);
uint16_t test_cmd_hostapi_pqc_ml_kem_ex(const test_cmd_st *cmd, test_rsp_st *rsp);

extern cmd_proc_func_t g_test_cmd_table[CMD_MAX_COUNT];
extern const char* g_test_cmd_names[CMD_MAX_COUNT];
