#ifndef EHSM_DRV_VERSION_H
#define EHSM_DRV_VERSION_H

#define EHSM_DRV_VERSION_MAJOR 2
#define EHSM_DRV_VERSION_MINOR 3
#define EHSM_DRV_VERSION_PATCH 1

#define EHSM_DRV_VERSION_PRE_RELEASE ""

#endif // EHSM_DRV_VERSION_H
