#ifndef EHSM_DRV_VERSION_H
#define EHSM_DRV_VERSION_H

#define EHSM_DRV_VERSION_MAJOR 2
#define EHSM_DRV_VERSION_MINOR 0
#define EHSM_DRV_VERSION_PATCH 0

#define EHSM_DRV_VERSION_PRE_RELEASE "rc.9"

#endif // EHSM_DRV_VERSION_H
