/* Generated by mbgen v0.1 at 2025-03-24 11:43:59, do NOT change content directly */

#ifndef BL_MB_H
#define BL_MB_H

#include "ehsmdrv/basic/types.h"

#pragma pack(1)

/* ---- group 全局定义 ---- */
/*   */

/* ---- group BootLoader功能 ---- */
/* BootLoader提供的功能命令。  */

/* ---- command bl_read_ver start ---- */

#define MB_CMD_ID_BL_READ_VER 0xff10U /* Command ID for bl_read_ver*/

/* struct bl_read_ver, 读取版本命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff10 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t ver_addr;     /* [offset: 12] 版本信息缓冲区的host地址。 */
    uint32_t ver_size;    /* [offset: 20] 版本缓冲区的大小。 */
} mb_cmd_bl_read_ver_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_read_ver_st;

/* ---- command bl_read_ver end ---- */

/* ---- command bl_otp_read start ---- */

#define MB_CMD_ID_BL_OTP_READ 0xff02U /* Command ID for bl_otp_read*/

/* struct bl_otp_read, 读取OTP命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff02 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_src_addr; /* [offset: 12] eHSM内部的OTP地址，数据从此地址读取。 */
    uint32_t size;         /* [offset: 20] 要读取的数据的字节大小。 */
    raddr_t host_dst_addr; /* [offset: 24] host地址，数据将写入此地址。 */
} mb_cmd_bl_otp_read_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_otp_read_st;

/* ---- command bl_otp_read end ---- */

/* ---- command bl_otp_write start ---- */

#define MB_CMD_ID_BL_OTP_WRITE 0xff01U /* Command ID for bl_otp_write*/

/* struct bl_otp_write, 读取OTP命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff01 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_dst_addr; /* [offset: 12] eHSM地址，数据将写入此地址。请注意，OTP只能写入一次。 */
    uint32_t size;         /* [offset: 20] 要写入的数据的字节大小。 */
    raddr_t host_src_addr; /* [offset: 24] host地址，数据从此地址读取。 */
} mb_cmd_bl_otp_write_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_otp_write_st;

/* ---- command bl_otp_write end ---- */

/* ---- command bl_reg_rd start ---- */

#define MB_CMD_ID_BL_REG_RD 0xff24U /* Command ID for bl_reg_rd*/

/* struct bl_reg_rd, CFG数据读取命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff24 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_src_addr; /* [offset: 12] eHSM地址，数据将从此地址读取。 */
    uint32_t size;         /* [offset: 20] 要读取的数据的字节大小。固件无需验证此值的有效性。 */
    raddr_t host_dst_addr; /* [offset: 24] host地址，数据将写入此地址。缓冲区应有足够的大小。 */
} mb_cmd_bl_reg_rd_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_reg_rd_st;

/* ---- command bl_reg_rd end ---- */

/* ---- command bl_reg_wr start ---- */

#define MB_CMD_ID_BL_REG_WR 0xff23U /* Command ID for bl_reg_wr*/

/* struct bl_reg_wr, CFG数据写入命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff23 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_dst_addr; /* [offset: 12] eHSM地址，数据将被写入此地址。 */
    uint32_t size;         /* [offset: 20] 要写入的数据的字节大小。 */
    raddr_t host_src_addr; /* [offset: 24] host地址，数据将从此地址读取。 */
} mb_cmd_bl_reg_wr_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_reg_wr_st;

/* ---- command bl_reg_wr end ---- */

/* ---- command bl_fw_upgrade start ---- */

#define MB_CMD_ID_BL_FW_UPGRADE 0xff05U /* Command ID for bl_fw_upgrade*/

/* struct bl_fw_upgrade, 固件镜像升级命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff05 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t process_mode;  /* [offset: 12] 处理模式。 */
    uint8_t reserved1[19]; /* [offset: 13] reserved */
    raddr_t image_addr;    /* [offset: 32] 镜像地址。 */
    uint32_t image_size;   /* [offset: 40] 升级镜像的大小（以字节为单位）。 */
    raddr_t storage_addr;  /* [offset: 44] 镜像存储地址 */
} mb_cmd_bl_fw_upgrade_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_fw_upgrade_st;

/* ---- command bl_fw_upgrade end ---- */

/* ---- command bl_verify_image start ---- */

#define MB_CMD_ID_BL_VERIFY_IMAGE 0xff06U /* Command ID for bl_verify_image*/

#define MB_BL_VERIFY_IMAGE_CHECK_VERSION_OFF     0x00U /*  */
#define MB_BL_VERIFY_IMAGE_CHECK_VERSION_ON      0x01U /*  */
#define MB_BL_VERIFY_IMAGE_BOOT_AFTER_VERIFY_ON  0x01U /*  */
#define MB_BL_VERIFY_IMAGE_BOOT_AFTER_VERIFY_OFF 0x00U /*  */
#define MB_BL_VERIFY_IMAGE_ONLY_COPY_CODE_YES    0x01U /*  */
#define MB_BL_VERIFY_IMAGE_ONLY_COPY_CODE_NO     0x00U /*  */

/* struct bl_verify_image, 镜像校验命令。 */
typedef struct {
    uint16_t cmd_id;           /* [offset: 0] 0xff06 */
    uint16_t cmd_id_inv;       /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[10];     /* [offset: 4] reserved */
    uint8_t check_version;     /* [offset: 14] 是否检查版本计数器。 */
    uint8_t boot_after_verify; /* [offset: 15] 验证成功后是否启动eHSM FW。 */
    raddr_t image_addr;        /* [offset: 16] 如果code_addr为0，则是完整镜像的host地址；否则是镜像头的host地址。 */
    uint32_t image_size;       /* [offset: 24] 镜像的大小（以字节为单位），包括镜像头和code区。 */
    raddr_t image_out_addr;    /* [offset: 28] 镜像解密后（如果镜像中是明文，则复制）存储到的host地址。 */
    raddr_t code_addr; /* [offset: 36] 代码的host地址，如果code_addr为0，则code存储在image_addr指向的镜像头后面。 */
    uint8_t only_copy_code; /* [offset: 44] 是否仅将代码复制到image_out_addr。 */
} mb_cmd_bl_verify_image_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_verify_image_st;

/* ---- command bl_verify_image end ---- */

/* ---- command bl_get_random_key start ---- */

#define MB_CMD_ID_BL_GET_RANDOM_KEY 0xff08U /* Command ID for bl_get_random_key*/

/* struct bl_get_random_key, 生成随机密钥命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff08 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t key_level;     /* [offset: 12] eHSM或SOC密钥 */
    uint8_t key_type;      /* [offset: 13] 密钥类型。 */
    uint8_t reserved1[26]; /* [offset: 14] reserved */
    raddr_t key_addr;      /* [offset: 40] 输出加密随机密钥和4字节CRC32值的host地址。 */
} mb_cmd_bl_get_random_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_get_random_key_st;

/* ---- command bl_get_random_key end ---- */

/* ---- command bl_encrypt_key start ---- */

#define MB_CMD_ID_BL_ENCRYPT_KEY 0xff09U /* Command ID for bl_encrypt_key*/

/* struct bl_encrypt_key, 加密密钥命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff09 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t key_level;     /* [offset: 12] eHSM或SOC密钥 */
    uint8_t reserved1[19]; /* [offset: 13] reserved */
    raddr_t
        input_addr;      /* [offset: 32]
                            输入对称密钥或非对称密钥的私钥（只支持SM2或SECP256R1）或公钥哈希的host地址。32字节密钥（或哈希）+
                            4字节密钥（或哈希）的CRC值，用0x00填充至48字节，并使用RTL（eHSM/SOC）KEK加密的结果。 */
    uint32_t input_size; /* [offset: 40] 输入密钥或HASH的大小，必须为48字节。 */
    raddr_t output_addr; /* [offset: 44] 存储加密密钥或HASH以及32字节大小的加密密钥的4字节CRC32值的host地址。 */
} mb_cmd_bl_encrypt_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_encrypt_key_st;

/* ---- command bl_encrypt_key end ---- */

/* ---- command bl_get_challenge start ---- */

#define MB_CMD_ID_BL_GET_CHALLENGE 0xff03U /* Command ID for bl_get_challenge*/

/* struct bl_get_challenge, 获取挑战值命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff03 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t type;          /* [offset: 12] 获取挑战值的类型。 */
    uint8_t reserved1[35]; /* [offset: 13] reserved */
    raddr_t addr;          /* [offset: 48] 存储挑战值的host地址。 */
} mb_cmd_bl_get_challenge_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_get_challenge_st;

/* ---- command bl_get_challenge end ---- */

/* ---- command bl_debug_auth start ---- */

#define MB_CMD_ID_BL_DEBUG_AUTH 0xff04U /* Command ID for bl_debug_auth*/

#define MB_BL_DEBUG_AUTH_ALG_SM2_WITH_SM3             0x01U /* SM3-SM2 */
#define MB_BL_DEBUG_AUTH_ALG_ECCSECP256R1_WITH_SHA256 0x02U /* SHA256-SECP256R1 */
#define MB_BL_DEBUG_AUTH_ALG_SM4_CMAC                 0x03U /* SM4-CMAC */
#define MB_BL_DEBUG_AUTH_ALG_AES128_CMAC              0x04U /* AES128-CMAC */
#define MB_BL_DEBUG_AUTH_ALG_SHA256_RSA               0x05U /* SHA256_RSA */

/* struct bl_debug_auth, 调试认证命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff04 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t type;          /* [offset: 12] 之前获取挑战值的类型。 */
    uint8_t alg;           /* [offset: 13] 验证算法。 */
    uint8_t reserved1[10]; /* [offset: 14] reserved */
    raddr_t sign_addr;     /* [offset: 24] 签名的host地址。 */
    uint32_t sign_size;    /* [offset: 32] 签名的字节大小。 */
    raddr_t pub_addr;      /* [offset: 36] 签名使用的公钥的host地址。 */
    uint32_t pub_size;     /* [offset: 44] 签名者公钥的字节大小。 */
    raddr_t
        soc_dbg_bitmap_addr;      /* [offset: 48]
                                     SOC调试认证位图数据的host地址。仅对SOC调试认证有效。前4个字对应寄存器SYS_WR_SOC_DBG_EN_128B0至SYS_WR_SOC_DBG_EN_128B3（为1的位表示打开对应端口，为0的位表示不改变对应端口状态）。最后一个字对应SYS_WR_SOC_DBG_EN（仅bit0有效）。
                                   */
    uint32_t soc_dbg_bitmap_size; /* [offset: 56] SOC调试身份验证位图数据的大小。固定长度（5个字）。 */
} mb_cmd_bl_debug_auth_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_debug_auth_st;

/* ---- command bl_debug_auth end ---- */

/* ---- command bl_close_debug start ---- */

#define MB_CMD_ID_BL_CLOSE_DEBUG 0xff0eU /* Command ID for bl_close_debug*/

/* struct bl_close_debug, 关闭调试功能。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff0e */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t type;         /* [offset: 12] 关闭调试的类型。 */
    uint8_t reserved1[3]; /* [offset: 13] reserved */
    raddr_t
        soc_dbg_bitmap_addr;      /* [offset: 16]
                                     SoC调试认证位图数据的host地址。仅对SoC调试认证有效。大小为5个字，前4个字表示是否按位关闭相应的硬件调试端口（为1的位表示关闭对应端口，为0的位表示不改变对应端口状态）。最后一个字仅最低位有效（表示是否关闭129位的硬件调试端口）。
                                   */
    uint32_t soc_dbg_bitmap_size; /* [offset: 24] SOC调试身份验证位图数据的大小。固定长度（5个字）。 */
} mb_cmd_bl_close_debug_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_close_debug_st;

/* ---- command bl_close_debug end ---- */

/* ---- command bl_set_uart_baudrate start ---- */

#define MB_CMD_ID_BL_SET_UART_BAUDRATE 0x0f04U /* Command ID for bl_set_uart_baudrate*/

/* struct bl_set_uart_baudrate, 设置UART波特率的命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0f04 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
    uint32_t baud_div;   /* [offset: 4] UART的频率分频值，指CPU频率值除以UART波特率值的结果。 */
} mb_cmd_bl_set_uart_baudrate_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_set_uart_baudrate_st;

/* ---- command bl_set_uart_baudrate end ---- */

/* ---- command bl_self_test start ---- */

#define MB_CMD_ID_BL_SELF_TEST 0x0020U /* Command ID for bl_self_test*/

/* struct bl_self_test, 自检命令。将测试所有支持的算法类型。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0020 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
} mb_cmd_bl_self_test_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_self_test_st;

/* ---- command bl_self_test end ---- */

/* ---- command bl_read_self_test_result start ---- */

#define MB_CMD_ID_BL_READ_SELF_TEST_RESULT 0xff11U /* Command ID for bl_read_self_test_result*/

/* struct bl_read_self_test_result, 读取自检结果的命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff11 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t
        result_addr; /* [offset: 12]
                        自检结果存储的host地址。结果包含两个字，第一个字表示已测试的算法，第二个字表示每个算法的结果。由对应的位标志组合而成。
                      */
} mb_cmd_bl_read_self_test_result_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_read_self_test_result_st;

/* ---- command bl_read_self_test_result end ---- */

/* ---- command bl_fw_auth start ---- */

#define MB_CMD_ID_BL_FW_AUTH 0xff12U /* Command ID for bl_fw_auth*/

#define MB_BL_FW_AUTH_TYPE_DEL_USER_KEY       0x01U /* 删除给定的用户密钥 */
#define MB_BL_FW_AUTH_TYPE_MODIFY_VER_COUNTER 0x02U /* 修改eHSM的版本计数器 */
#define MB_BL_FW_AUTH_TYPE_DESTROY_MODE       0x03U /* 进入销毁模式，删除所有密钥 */

/* struct bl_fw_auth, 固件认证命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff12 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t type;         /* [offset: 12] 认证类型。 */
    uint8_t reserved1[3]; /* [offset: 13] reserved */
    uint8_t arg[16];      /* [offset: 16] 当类型为1时，arg表示用户密钥ID；当类型为2时，表示新的版本计数器；否则忽略。 */
    uint8_t auth_data[32]; /* [offset: 32] 认证数据。 */
    raddr_t out_addr;      /* [offset: 64] OTP 输出buffer，可以为NULL， 当不为NULL时，应当至少有720字节空间. */
} mb_cmd_bl_fw_auth_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_bl_fw_auth_st;

/* ---- command bl_fw_auth end ---- */



#pragma pack()

#endif
