/* Generated by mbgen v0.1 at 2025-03-24 11:44:04, do NOT change content directly */

#ifndef MB_H
#define MB_H

#include "ehsmdrv/basic/types.h"

#pragma pack(1)

/* ---- group 全局定义 ---- */
/*   */

/* enum process_mode */
#define MB_START       0x01U /* 三段式处理的开始阶段 */
#define MB_UPDATE      0x02U /* 三段式处理的更新数据阶段 */
#define MB_STREAMSTART 0x03U /* 三段式处理的开始和更新阶段 */
#define MB_FINISH      0x04U /* 三段式处理的结束阶段 */
#define MB_ONE_PASS    0x07U /* 一次性处理 */

/* enum mac_direction */
#define MB_MAC_GEN 0x00U /* 生成MAC值 */
#define MB_MAC_VRY 0x01U /* 校验MAC值 */

/* enum key_type */
#define MB_KEY_HANDLE 0x00U /* 算法指令使用密钥句柄 */
#define MB_PLAIN_KEY  0x01U /* 算法指令使用明文密钥 */
/* enum sig_direction */
#define MB_SIG_VRY 0x00U /* 校验签名值 */
#define MB_SIG_GEN 0x01U /* 生成签名值 */

/* enum cipher_direction */
#define MB_CIPHER_ENC 0x00U /* 加密 */
#define MB_CIPHER_DEC 0x01U /* 解密 */

/* enum sm9_enc_type */
#define MB_SM9_ENC_TYPE_SM3 0x00U /* KDF 基于流密码（使用 SM3 算法）。 */
#define MB_SM9_ENC_TYPE_SM4 0x01U /* KDF 基于块密码（使用 SM4 算法）。 */

/* enum sm9_padding_type */
#define MB_SM9_PADDING_NO  0x00U /* 无填充，明文长度应为块密码的倍数。 */
#define MB_SM9_PADDING_YES 0x01U /* 在明文中使用 PKCS7 填充。 */

/* enum debug_auth_challenge_type */
#define MB_EHSM_CHALLENGE_TYPE_EHSM_DEBUG 0x01U /* eHSM调试身份验证 */
#define MB_EHSM_CHALLENGE_TYPE_SHE_DEBUG  0x02U /* SHE调试身份验证 */
#define MB_EHSM_CHALLENGE_TYPE_SOC_DEBUG  0x03U /* SOC调试身份验证 */
#define MB_EHSM_CHALLENGE_TYPE_USER_AUTH  0x04U /* 用户调试身份验证 */
#define MB_EHSM_CHALLENGE_TYPE_FW_AUTH    0x05U /* 固件身份验证 */

/* enum key_algo_id */
#define MB_DES                  0x01U /* DES密钥 */
#define MB_TDES_128             0x02U /* TDES-128密钥 */
#define MB_TDES_192             0x03U /* TDES-192密钥 */
#define MB_AES_128              0x04U /* AES-128密钥 */
#define MB_AES_192              0x05U /* AES-192密钥 */
#define MB_AES_256              0x06U /* AES-256密钥 */
#define MB_SM4                  0x07U /* SM4密钥 */
#define MB_SM2                  0x08U /* SM2密钥 */
#define MB_RSA_1024             0x09U /* RSA1024密钥 */
#define MB_RSA_2048             0x0aU /* RSA2048密钥 */
#define MB_RSA_3072             0x0bU /* RSA3072密钥 */
#define MB_RSA_4096             0x0cU /* RSA4096密钥 */
#define MB_RSA_1024_CRT         0x0dU /* RSA1024-CRT密钥 */
#define MB_RSA_2048_CRT         0x0eU /* RSA2048-CRT密钥 */
#define MB_RSA_3072_CRT         0x0fU /* RSA3072-CRT密钥 */
#define MB_RSA_4096_CRT         0x10U /* RSA4096-CRT密钥 */
#define MB_DH                   0x11U /* DH密钥 */
#define MB_ECC_BRAINPOOLP_160R1 0x12U /* ECC Brainpool p160r1曲线密钥 */
#define MB_ECC_BRAINPOOLP_192R1 0x13U /* ECC Brainpool p192r1曲线密钥 */
#define MB_ECC_BRAINPOOLP_224R1 0x14U /* ECC Brainpool p224r1曲线密钥 */
#define MB_ECC_BRAINPOOLP_256R1 0x15U /* ECC Brainpool p256r1曲线密钥 */
#define MB_ECC_BRAINPOOLP_320R1 0x16U /* ECC Brainpool p320r1曲线密钥 */
#define MB_ECC_BRAINPOOLP_384R1 0x17U /* ECC Brainpool p384r1曲线密钥 */
#define MB_ECC_BRAINPOOLP_512R1 0x18U /* ECC Brainpool p512r1曲线密钥 */
#define MB_ECC_SECP_192R1       0x19U /* ECC secp192r1曲线密钥 */
#define MB_ECC_SECP_224R1       0x1aU /* ECC secp224r1曲线密钥 */
#define MB_ECC_SECP_256R1       0x1bU /* ECC secp256r1曲线密钥 */
#define MB_ECC_SECP_384R1       0x1cU /* ECC secp384r1曲线密钥 */
#define MB_ECC_SECP_521R1       0x1dU /* ECC secp521r1曲线密钥 */
#define MB_ED25519              0x1eU /* 爱德华曲线密钥 */
#define MB_X25519               0x1fU /* 蒙哥马利曲线密钥 */
#define MB_SM4_XTS              0x20U /* SM4-XTS密钥 */
#define MB_AES_128_XTS          0x21U /* AES-128-XTS密钥 */
#define MB_AES_192_XTS          0x22U /* AES-192-XTS密钥 */
#define MB_AES_256_XTS          0x23U /* AES-256-XTS密钥 */
#define MB_CHACHA               0x24U /* CHACHA密钥 */
#define MB_HMAC                 0x25U /* HMAC密钥 */
#define MB_ECC_SECP_160K1       0x26U /* ECC secp160k1密钥 */
#define MB_ECC_SECP_192K1       0x27U /* ECC secp192k1密钥 */
#define MB_ECC_SECP_224K1       0x28U /* ECC secp224k1密钥 */
#define MB_ECC_SECP_256K1       0x29U /* ECC secp256k1密钥 */
#define MB_SM9_ENC_USERPRIV     0x2aU /* SM9用户加密私钥 */
#define MB_SM9_SIGN_USERPRIV    0x2bU /* SM9用户签名私钥 */
#define MB_SM9_EXCHG_USERPRIV   0x2cU /* SM9用户交换私钥 */
#define MB_SM9_EXCHG_TEMP       0x2dU /* SM9临时交换密钥 */

/* enum usage_permit_flags */
#define MB_KEY_USAGE_NONE                0x00U    /*  */
#define MB_KEY_USAGE_SIGN                0x01U    /* 密钥可用于签名或生成MAC/HMAC */
#define MB_KEY_USAGE_VERIFY              0x02U    /* 密钥可用于验签或验证MAC/HMAC */
#define MB_KEY_USAGE_ENCRYPT             0x04U    /* 密钥可用于加密 */
#define MB_KEY_USAGE_DECRYPT             0x08U    /* 密钥可用于解密 */
#define MB_KEY_USAGE_TIMESTAMP           0x10U    /* 密钥可用于时间戳功能 */
#define MB_KEY_USAGE_SECUREBOOT          0x20U    /* 密钥可用于安全启动 */
#define MB_KEY_USAGE_SECURESTORAGE       0x40U    /* 密钥可用于安全存储 */
#define MB_KEY_USAGE_KEYCREATION         0x80U    /* 密钥可用于派生或协商新密钥 */
#define MB_KEY_USAGE_CREATION_TRANSP_KEY 0x100U   /* 密钥可用于派生传输密钥 */
#define MB_KEY_USAGE_UTCSYNC             0x200U   /* 密钥可用于UTC同步 */
#define MB_KEY_USAGE_TRANSPORT           0x400U   /* 密钥可作为传输密钥使用 */
#define MB_KEY_PERMIT_REMOVE             0x800U   /* 密钥可以被移除 */
#define MB_KEY_PERMIT_IMPORT_PLAINTEXT   0x1000U  /* 密钥可以被明文导入 */
#define MB_KEY_PERMIT_IMPORT_CIPHERTEXT  0x2000U  /* 密钥可以被密文导入 */
#define MB_KEY_PERMIT_EXPORT_PLAINTEXT   0x4000U  /* 密钥可以被明文导出 */
#define MB_KEY_PERMIT_EXPORT_CIPHERTEXT  0x8000U  /* 密钥可以被密文导出 */
#define MB_KEY_PERMIT_BOOT_FIAL_USAGE    0x10000U /* 密钥在启动失败后可以使用 */
#define MB_KEY_PERMIT_DEBUG_USAGE        0x20000U /* 密钥可在调试时使用 */
#define MB_KEY_PERMIT_WILDCARD_PRT       0x40000U /* 不用指定UID更新密钥 */
#define MB_KEY_PERMIT_WR_PRT             0x80000U /* 密钥写保护（不能覆盖） */

/* enum sm9_exchg_role */
#define MB_SM9_EXCHG_ROLE_SPONSOR   0x00U /* 在SM9密钥交换中作为发起方 */
#define MB_SM9_EXCHG_ROLE_RESPONSOR 0x01U /* 在SM9密钥交换中作为响应方 */

/*Indicate mssage type used for sm2/ecdsa/rsa signature and verify*/
#define MB_MSG_TYPE_MESSAGE 0x00 /* 消息类型：原始消息（未经过哈希处理） */
#define MB_MSG_TYPE_DIGEST  0x01 /* 消息类型：摘要数据（已通过哈希算法处理） */

/* ---- group 对称算法 ---- */
/* 这些命令定义了对称的加解密算法，包括普通的加解密和AEAD、CHACHA算法。  */

/* ---- command symm_cipher start ---- */

#define MB_CMD_ID_SYMM_CIPHER 0x0101U /* Command ID for symm_cipher*/

#define MB_SYMM_CIPHER_PADDING_NO_PADDING   0x00U /* 无填充 */
#define MB_SYMM_CIPHER_PADDING_PKCS7        0x02U /* PKCS7填充 */
#define MB_SYMM_CIPHER_PADDING_ONEWITHZEROS 0x03U /* ONEWITHZEROS (ISO-7816-4) */
#define MB_SYMM_CIPHER_ALGORITHM_DES        0x00U /* DES对称加密算法 */
#define MB_SYMM_CIPHER_ALGORITHM_TDES_128   0x01U /* TDES-128对称加密算法 */
#define MB_SYMM_CIPHER_ALGORITHM_TDES_192   0x02U /* TDES-192对称加密算法 */
#define MB_SYMM_CIPHER_ALGORITHM_AES_128    0x05U /* AES-128对称加密算法 */
#define MB_SYMM_CIPHER_ALGORITHM_AES_192    0x06U /* AES-192对称加密算法 */
#define MB_SYMM_CIPHER_ALGORITHM_AES_256    0x07U /* AES-256对称加密算法 */
#define MB_SYMM_CIPHER_ALGORITHM_SM4        0x08U /* 国密SM4对称加密算法 */
#define MB_SYMM_CIPHER_CIPHER_MODE_ECB      0x01U /* 对称加密的ECB模式 */
#define MB_SYMM_CIPHER_CIPHER_MODE_XTS      0x02U /* 对称加密的XTS模式 */
#define MB_SYMM_CIPHER_CIPHER_MODE_CBC      0x03U /* 对称加密的CBC模式 */
#define MB_SYMM_CIPHER_CIPHER_MODE_CFB      0x04U /* 对称加密的CFB模式 */
#define MB_SYMM_CIPHER_CIPHER_MODE_OFB      0x05U /* 对称加密的OFB模式 */
#define MB_SYMM_CIPHER_CIPHER_MODE_CTR      0x06U /* 对称加密的CTR模式 */

/* struct symm_cipher, 对称加解密算法操作。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0101 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];    /* [offset: 4] reserved */
    uint8_t key_type;        /* [offset: 11] 密钥类型 */
    uint8_t process_mode;    /* [offset: 12] 处理模式。 */
    uint8_t direction;       /* [offset: 13] 加密方向。 */
    uint8_t padding;         /* [offset: 14] 填充类型。 */
    uint8_t algorithm;       /* [offset: 15] 对称加密算法。 */
    uint8_t cipher_mode;     /* [offset: 16] 对称加密模式。 */
    uint8_t reserved1[3];    /* [offset: 17] reserved */
    uint32_t key_handle;     /* [offset: 20] 用于操作的密钥。START/UPDATE/FINISH/ONE-PASS 模式应设置。 */
    uint8_t reserved2[12];   /* [offset: 24] reserved */
    raddr_t input_addr;      /* [offset: 36] 输入明文（加密模式）或密文（解密模式）的地址。 */
    uint32_t input_size;     /* [offset: 44] 输入文本的大小。 */
    raddr_t output_addr;     /* [offset: 48] 输出明文或密文的地址。 */
    uint32_t output_size;    /* [offset: 56] 输出缓冲区的大小。 */
    raddr_t iv_addr;         /* [offset: 60] 初始化向量/Nonce 的地址。 */
    uint32_t iv_size;        /* [offset: 68] 初始化向量/Nonce 的大小。 */
    raddr_t context;         /* [offset: 72] 加密上下文。 */
    uint32_t context_size;   /* [offset: 80] 加密上下文的长度。 */
    raddr_t plain_key_addr;  /* [offset: 84] 明文密钥，key_type为1时有效 */
    uint32_t plain_key_size; /* [offset: 92] 明文密钥长度，key_type为1时有效 */
} mb_cmd_symm_cipher_st;

/* response struct */
typedef struct {
    uint32_t ret_code;    /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t output_size; /* [offset: 4] 输出明文或密文的大小 */
} mb_rsp_symm_cipher_st;

/* ---- command symm_cipher end ---- */

/* ---- command aead_gcm start ---- */

#define MB_CMD_ID_AEAD_GCM 0x0102U /* Command ID for aead_gcm*/

#define MB_AEAD_GCM_ALGORITHM_AES_128 0x05U /*  */
#define MB_AEAD_GCM_ALGORITHM_AES_192 0x06U /*  */
#define MB_AEAD_GCM_ALGORITHM_AES_256 0x07U /*  */
#define MB_AEAD_GCM_ALGORITHM_SM4     0x08U /*  */

/* struct aead_gcm, AEAD 的 GCM 模式加解密命令。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0102 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];    /* [offset: 4] reserved */
    uint8_t key_type;        /* [offset: 11] 密钥类型 */
    uint8_t process_mode;    /* [offset: 12] 处理模式。 */
    uint8_t direction;       /* [offset: 13] 加密方向。 */
    uint8_t reserved1[1];    /* [offset: 14] reserved */
    uint8_t algorithm;       /* [offset: 15] 对称加密算法。 */
    uint8_t reserved2[4];    /* [offset: 16] reserved */
    uint32_t key_handle;     /* [offset: 20] 用于操作的密钥。 */
    uint8_t reserved3[12];   /* [offset: 24] reserved */
    raddr_t input_addr;      /* [offset: 36] GCM 输入数据的地址。 */
    uint32_t input_size;     /* [offset: 44] 输入明文或密文的长度。 */
    raddr_t output_addr;     /* [offset: 48] GCM 输出数据的地址。 */
    uint32_t output_size;    /* [offset: 56] 输出缓冲区的大小。 */
    raddr_t aad_addr;        /* [offset: 60] GCM 关联数据的地址。 */
    uint32_t aad_size;       /* [offset: 68] 关联数据的字节长度，不应大于 128。 */
    raddr_t tag_addr;        /* [offset: 72] GCM 标签的地址。 */
    uint32_t tag_size;       /* [offset: 80] 标签长度。标签大小应在 1 到 16 的范围内。 */
    raddr_t iv_addr;         /* [offset: 84] 初始化向量/Nonce 的地址。 */
    uint32_t iv_size;        /* [offset: 92] IV 的字节长度应为 12 字节。 */
    raddr_t context;         /* [offset: 96] 加密上下文。 */
    uint32_t context_size;   /* [offset: 104] 加密上下文的长度。 */
    raddr_t plain_key_addr;  /* [offset: 108] 明文密钥，key_type为1时有效 */
    uint32_t plain_key_size; /* [offset: 116] 明文密钥长度，key_type为1时有效。 */
} mb_cmd_aead_gcm_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t output_size;  /* [offset: 4] 输出明文或密文的大小 */
    uint32_t verification; /* [offset: 8] 解密服务中标签验证的结果。0 表示成功，其他表示失败。加密时忽略。 */
} mb_rsp_aead_gcm_st;

/* ---- command aead_gcm end ---- */

/* ---- command aead_ccm start ---- */

#define MB_CMD_ID_AEAD_CCM 0x0103U /* Command ID for aead_ccm*/

#define MB_AEAD_CCM_ALGORITHM_AES_128 0x05U /*  */
#define MB_AEAD_CCM_ALGORITHM_AES_192 0x06U /*  */
#define MB_AEAD_CCM_ALGORITHM_AES_256 0x07U /*  */
#define MB_AEAD_CCM_ALGORITHM_SM4     0x08U /*  */

/* struct aead_ccm, AEAD 的 CCM 模式加解密命令。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0103 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];    /* [offset: 4] reserved */
    uint8_t key_type;        /* [offset: 11] 密钥类型 */
    uint8_t process_mode;    /* [offset: 12] 处理模式。 */
    uint8_t direction;       /* [offset: 13] 加密方向。 */
    uint8_t reserved1[1];    /* [offset: 14] reserved */
    uint8_t algorithm;       /* [offset: 15] 对称加密算法。 */
    uint8_t reserved2[4];    /* [offset: 16] reserved */
    uint32_t key_handle;     /* [offset: 20] 用于操作的密钥。 */
    uint8_t reserved3[12];   /* [offset: 24] reserved */
    raddr_t input_addr;      /* [offset: 36] CCM 输入数据的地址。 */
    uint32_t input_size;     /* [offset: 44] 输入明文或密文的长度。 */
    raddr_t output_addr;     /* [offset: 48] CCM 输入结构数据的地址。 */
    uint32_t output_size;    /* [offset: 56] 输出缓冲区的大小。 */
    raddr_t aad_addr;        /* [offset: 60] CCM 关联数据的地址。 */
    uint32_t aad_size;       /* [offset: 68] 关联数据的字节长度，不应大于 128。 */
    raddr_t tag_addr;        /* [offset: 72] CCM 标签的地址。 */
    uint32_t tag_size;       /* [offset: 80] 标签长度。标签大小应在 1 到 16 的范围内。 */
    raddr_t nonce_addr;      /* [offset: 84] nonce 的地址。 */
    uint32_t nonce_size;     /* [offset: 92] nonce 的字节长度。范围在 [7, 13]。 */
    raddr_t context;         /* [offset: 96] 加密上下文。 */
    uint32_t context_size;   /* [offset: 104] 加密上下文的长度。 */
    raddr_t plain_key_addr;  /* [offset: 108] 明文密钥，key_type为1时有效。 */
    uint32_t plain_key_size; /* [offset: 116] 明文密钥长度，key_type为1时有效。 */
} mb_cmd_aead_ccm_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t output_size;  /* [offset: 4] 输出明文或密文的大小 */
    uint32_t verification; /* [offset: 8] 解密服务中标签验证的结果。0 表示成功，其他表示失败。加密时忽略。 */
} mb_rsp_aead_ccm_st;

/* ---- command aead_ccm end ---- */

/* ---- command chacha_cipher start ---- */

#define MB_CMD_ID_CHACHA_CIPHER 0x0104U /* Command ID for chacha_cipher*/

/* struct chacha_cipher, chacha20-poly1305 加解密命令。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0104 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];    /* [offset: 4] reserved */
    uint8_t key_type;        /* [offset: 11] 密钥类型 */
    uint8_t process_mode;    /* [offset: 12] 处理模式。 */
    uint8_t direction;       /* [offset: 13] 加密方向。 */
    uint8_t reserved1[2];    /* [offset: 14] reserved */
    uint32_t constant;       /* [offset: 16] chacha 的常数。 */
    uint32_t key_handle;     /* [offset: 20] 用于操作的密钥 */
    uint8_t reserved2[12];   /* [offset: 24] reserved */
    raddr_t input_addr;      /* [offset: 36] chacha 输入数据的地址。 */
    uint32_t input_size;     /* [offset: 44] 输入明文或密文的长度。 */
    raddr_t output_addr;     /* [offset: 48] 输出缓冲区地址。 */
    uint32_t output_size;    /* [offset: 56] 输出缓冲区的大小。 */
    raddr_t aad_addr;        /* [offset: 60] chacha 关联数据的地址。 */
    uint32_t aad_size;       /* [offset: 68] 关联数据的字节长度。 */
    raddr_t tag_addr;        /* [offset: 72] chacha 标签的地址。 */
    uint32_t tag_size;       /* [offset: 80] 标签长度。标签大小应在 1 到 16 的范围内。 */
    raddr_t nonce_addr;      /* [offset: 84] nonce 的地址。 */
    uint32_t nonce_size;     /* [offset: 92] nonce 的字节长度。必须为 8 字节。 */
    raddr_t context;         /* [offset: 96] 加密上下文 */
    uint32_t context_size;   /* [offset: 104] 加密上下文的长度 */
    raddr_t plain_key_addr;  /* [offset: 108] 明文密钥，key_type为1时有效。 */
    uint32_t plain_key_size; /* [offset: 116] 明文密钥长度，key_type为1时有效。 */
} mb_cmd_chacha_cipher_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint8_t reserved0[4];  /* [offset: 4] reserved */
    uint32_t verification; /* [offset: 8] 解密服务中标签验证的结果。0 表示成功，其他表示失败。加密时忽略。 */
} mb_rsp_chacha_cipher_st;

/* ---- command chacha_cipher end ---- */

/* ---- group 数据摘要算法 ---- */
/* 包括HASH、HMAC 算法命令  */

/* ---- command hash start ---- */

#define MB_CMD_ID_HASH 0x0301U /* Command ID for hash*/

#define MB_HASH_ALGORITHM_SM3        0x00U /*  */
#define MB_HASH_ALGORITHM_MD5        0x01U /*  */
#define MB_HASH_ALGORITHM_SHA256     0x02U /*  */
#define MB_HASH_ALGORITHM_SHA384     0x03U /*  */
#define MB_HASH_ALGORITHM_SHA512     0x04U /*  */
#define MB_HASH_ALGORITHM_SHA1       0x05U /*  */
#define MB_HASH_ALGORITHM_SHA224     0x06U /*  */
#define MB_HASH_ALGORITHM_SHA512_224 0x07U /*  */
#define MB_HASH_ALGORITHM_SHA512_256 0x08U /*  */
#define MB_HASH_ALGORITHM_SHA3_224   0x09U /*  */
#define MB_HASH_ALGORITHM_SHA3_256   0x0aU /*  */
#define MB_HASH_ALGORITHM_SHA3_384   0x0bU /*  */
#define MB_HASH_ALGORITHM_SHA3_512   0x0cU /*  */

/* struct hash, HASH算法命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0x0301 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];   /* [offset: 4] reserved */
    uint8_t process_mode;   /* [offset: 12] 处理模式。 */
    uint8_t reserved1[2];   /* [offset: 13] reserved */
    uint8_t algorithm;      /* [offset: 15] 哈希算法类型。 */
    uint8_t reserved2[20];  /* [offset: 16] reserved */
    raddr_t data;           /* [offset: 36] 用于生成哈希值的消息数据的地址。 */
    uint32_t data_size;     /* [offset: 44] 消息数据的长度。 */
    raddr_t digest;         /* [offset: 48] 用于存储HASH值的地址 */
    uint32_t digest_size;   /* [offset: 56] HASH缓冲区的长度 */
    uint8_t reserved3[12];  /* [offset: 60] reserved */
    raddr_t hash_ctx;       /* [offset: 72] HASH上下文的地址。 */
    uint32_t hash_ctx_size; /* [offset: 80] 上下文的长度。 */
} mb_cmd_hash_st;

/* response struct */
typedef struct {
    uint32_t ret_code;    /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t digest_size; /* [offset: 4] 输出HASH值的大小 */
} mb_rsp_hash_st;

/* ---- command hash end ---- */

/* ---- command hmac start ---- */

#define MB_CMD_ID_HMAC 0x0302U /* Command ID for hmac*/

#define MB_HMAC_ALGORITHM_SM3        0x00U /*  */
#define MB_HMAC_ALGORITHM_MD5        0x01U /*  */
#define MB_HMAC_ALGORITHM_SHA256     0x02U /*  */
#define MB_HMAC_ALGORITHM_SHA384     0x03U /*  */
#define MB_HMAC_ALGORITHM_SHA512     0x04U /*  */
#define MB_HMAC_ALGORITHM_SHA1       0x05U /*  */
#define MB_HMAC_ALGORITHM_SHA224     0x06U /*  */
#define MB_HMAC_ALGORITHM_SHA512_224 0x07U /*  */
#define MB_HMAC_ALGORITHM_SHA512_256 0x08U /*  */
#define MB_HMAC_ALGORITHM_SHA3_224   0x09U /*  */
#define MB_HMAC_ALGORITHM_SHA3_256   0x0aU /*  */
#define MB_HMAC_ALGORITHM_SHA3_384   0x0bU /*  */
#define MB_HMAC_ALGORITHM_SHA3_512   0x0cU /*  */

/* struct hmac, HMAC算法命令。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0302 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];    /* [offset: 4] reserved */
    uint8_t key_type;        /* [offset: 11] 密钥类型 */
    uint8_t process_mode;    /* [offset: 12] 处理模式。 */
    uint8_t direction;       /* [offset: 13] HMAC 方向。 */
    uint8_t reserved1[1];    /* [offset: 14] reserved */
    uint8_t algorithm;       /* [offset: 15] 用于 HMAC 的HASH算法类型。 */
    uint8_t reserved2[4];    /* [offset: 16] reserved */
    uint32_t key_handle;     /* [offset: 20] 用于生成 HMAC 的密钥。 */
    uint8_t reserved3[12];   /* [offset: 24] reserved */
    raddr_t data;            /* [offset: 36] 用于生成哈希值的消息数据的地址。 */
    uint32_t data_size;      /* [offset: 44] 消息数据的长度。 */
    raddr_t digest;          /* [offset: 48] 用于HMAC值的地址。 */
    uint32_t digest_size;    /* [offset: 56] HMAC缓冲区的长度。 */
    uint8_t reserved4[12];   /* [offset: 60] reserved */
    raddr_t hmac_ctx;        /* [offset: 72] HMAC上下文的地址。 */
    uint32_t hmac_ctx_size;  /* [offset: 80] 上下文的长度。 */
    raddr_t plain_key_addr;  /* [offset: 84] 明文密钥，key_type为1时有效。 */
    uint32_t plain_key_size; /* [offset: 92] 明文密钥长度，key_type为1时有效。 */
} mb_cmd_hmac_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t digest_size;  /* [offset: 4] 输出HMAC值的大小 */
    uint32_t verification; /* [offset: 8] 验证结果。0 表示成功，其他表示失败。生成 HMAC 时忽略。 */
} mb_rsp_hmac_st;

/* ---- command hmac end ---- */

/* ---- group MAC算法 ---- */
/* SKE MAC 算法命令  */

/* ---- command mac start ---- */

#define MB_CMD_ID_MAC 0x0201U /* Command ID for mac*/

#define MB_MAC_ALGORITHM_DES       0x00U /*  */
#define MB_MAC_ALGORITHM_TDES_128  0x01U /*  */
#define MB_MAC_ALGORITHM_TDES_192  0x02U /*  */
#define MB_MAC_ALGORITHM_AES_128   0x05U /*  */
#define MB_MAC_ALGORITHM_AES_192   0x06U /*  */
#define MB_MAC_ALGORITHM_AES_256   0x07U /*  */
#define MB_MAC_ALGORITHM_SM4       0x08U /*  */
#define MB_MAC_CIPHER_MODE_CMAC    0x07U /*  */
#define MB_MAC_CIPHER_MODE_CBC_MAC 0x08U /*  */
#define MB_MAC_CIPHER_MODE_GMAC    0x09U /*  */

/* struct mac, MAC 生成或验证命令。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0201 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];    /* [offset: 4] reserved */
    uint8_t key_type;        /* [offset: 11] 密钥类型 */
    uint8_t process_mode;    /* [offset: 12] 处理模式。 */
    uint8_t direction;       /* [offset: 13] MAC 方向。 */
    uint8_t reserved1[1];    /* [offset: 14] reserved */
    uint8_t algorithm;       /* [offset: 15] MAC 使用的对称算法。 */
    uint8_t cipher_mode;     /* [offset: 16] MAC加密模式。 */
    uint8_t reserved2[3];    /* [offset: 17] reserved */
    uint32_t key_handle;     /* [offset: 20] 用于生成/验证 MAC 的密钥。 */
    uint8_t reserved3[12];   /* [offset: 24] reserved */
    raddr_t data;            /* [offset: 36] 用于生成/验证 MAC 的消息数据的地址。 */
    uint32_t data_size;      /* [offset: 44] 消息数据的长度。 */
    raddr_t mac;             /* [offset: 48] 生成或验证后的 MAC 值的地址。 */
    uint32_t mac_size;       /* [offset: 56] MAC 缓冲区的长度或生成的 MAC 值的长度。 */
    raddr_t iv_addr;         /* [offset: 60] GMAC 的 IV 地址。仅支持 GMAC，且大小应为 12 字节。 */
    uint8_t reserved4[4];    /* [offset: 68] reserved */
    raddr_t mac_ctx;         /* [offset: 72] MAC 的上下文地址。 */
    uint32_t mac_ctx_size;   /* [offset: 80] 上下文的长度。 */
    raddr_t plain_key_addr;  /* [offset: 84] 明文密钥，key_type为1时有效。 */
    uint32_t plain_key_size; /* [offset: 92] 明文密钥长度，key_type为1时有效。 */
} mb_cmd_mac_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t mac_size;     /* [offset: 4] 输出 MAC 的大小。 */
    uint32_t verification; /* [offset: 8] 验证结果。0 表示成功，其他表示失败。生成 MAC 时忽略。 */
} mb_rsp_mac_st;

/* ---- command mac end ---- */

/* ---- group 非对称算法 ---- */
/* 非对称算法命令，包括SM2、RSA、ECDSA、SM9等非对称的签名及加解密算法。  */

/* ---- command sm2_cipher start ---- */

#define MB_CMD_ID_SM2_CIPHER 0x0401U /* Command ID for sm2_cipher*/

/* struct sm2_key, SM2明文密钥数据结构 */
typedef struct {
    uint8_t privkey[32]; /* [offset: 0] SM2私钥。 */
    uint8_t pubkey[65];  /* [offset: 32] SM2公钥。 */
} mb_sm2_key_st;

/* struct sm2_cipher, SM2 加解密算法命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0x0401 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];   /* [offset: 4] reserved */
    uint8_t key_type;       /* [offset: 11] 密钥类型 */
    uint8_t reserved1[1];   /* [offset: 12] reserved */
    uint8_t direction;      /* [offset: 13] 加密方向。 */
    uint8_t reserved2[6];   /* [offset: 14] reserved */
    uint32_t key_handle;    /* [offset: 20] 用于操作的密钥。 */
    uint8_t reserved3[12];  /* [offset: 24] reserved */
    raddr_t input_addr;     /* [offset: 36] 输入数据的地址。 */
    uint32_t input_size;    /* [offset: 44] 输入数据的长度。 */
    raddr_t output_addr;    /* [offset: 48] 输出数据的地址。 */
    uint32_t output_size;   /* [offset: 56] 输出缓冲区的长度。 */
    raddr_t plain_key_addr; /* [offset: 60] 明文密钥，key_type为1时有效。 */
} mb_cmd_sm2_cipher_st;

/* response struct */
typedef struct {
    uint32_t ret_code;    /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t output_size; /* [offset: 4] 输出明文或密文的大小。 */
} mb_rsp_sm2_cipher_st;

/* ---- command sm2_cipher end ---- */

/* ---- command sm2_sign start ---- */

#define MB_CMD_ID_SM2_SIGN 0x0402U /* Command ID for sm2_sign*/

/* struct sm2_sign, SM2 签名/验证命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0x0402 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];   /* [offset: 4] reserved */
    uint8_t key_type;       /* [offset: 11] 密钥类型 */
    uint8_t process_mode;   /* [offset: 12] 处理模式。 */
    uint8_t direction;      /* [offset: 13] 签名方向。 */
    uint8_t reserved1[5];   /* [offset: 14] reserved */
    uint8_t msg_type;       /* [offset: 14] 表示msg_addr地址指向的数据类型. 0x00:完整消息,
                               0x01:消息摘要(E值)，仅支持process_mode为ONEPASS */
    uint32_t key_handle;    /* [offset: 20] 用于操作的密钥。 */
    uint8_t reserved2[12];  /* [offset: 24] reserved */
    raddr_t msg_addr;       /* [offset: 36] 输入消息的地址。 */
    uint32_t msg_size;      /* [offset: 44] 输入消息的长度。 */
    raddr_t sign_addr;      /* [offset: 48] 签名值的地址。 */
    uint32_t sign_size;     /* [offset: 56] 签名缓冲区或签名值的大小。 */
    uint8_t reserved3[12];  /* [offset: 60] reserved */
    raddr_t sign_ctx;       /* [offset: 72] 签名或验证的上下文地址。 */
    uint32_t sign_ctx_size; /* [offset: 80] 上下文的长度。 */
    raddr_t plain_key_addr; /* [offset: 84] 明文密钥，key_type为1时有效。 */
} mb_cmd_sm2_sign_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t sign_size;    /* [offset: 4] 输出签名的大小。验证服务中忽略。 */
    uint32_t verification; /* [offset: 8] 验证结果。0 表示成功，其他表示失败。签名服务中忽略。 */
} mb_rsp_sm2_sign_st;

/* ---- command sm2_sign end ---- */

/* ---- command Rsa_cipher start ---- */

#define MB_CMD_ID_RSA_CIPHER 0x0501U /* Command ID for Rsa_cipher*/

/* struct rsa_key, RSA明文密钥数据结构 */
typedef struct {
    uint8_t crt_mode;     /* [offset: 0] CRT模式，1代表私钥时CRT模式。 */
    uint8_t reserved0[3]; /* [offset: 1] reserved */
    uint32_t n_byte_sz;   /* [offset: 4] n值的字节数 */
    uint32_t e_byte_sz;   /* [offset: 8] e值的字节数 */
    raddr_t n;            /* [offset: 12] n值的存储地址 */
    raddr_t e;            /* [offset: 20] e值的存储地址 */
    raddr_t d;            /* [offset: 28] d值的存储地址 */
    raddr_t p;            /* [offset: 36] p值的存储地址 */
    raddr_t q;            /* [offset: 44] q值的存储地址 */
    raddr_t dp;           /* [offset: 52] dp值的存储地址 */
    raddr_t dq;           /* [offset: 60] dq值的存储地址 */
    raddr_t u;            /* [offset: 68] u值的存储地址 */
} mb_rsa_key_st;

/* struct Rsa_cipher, RSA 加密/解密命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0x0501 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];   /* [offset: 4] reserved */
    uint8_t key_type;       /* [offset: 11] 密钥类型 */
    uint8_t reserved1[1];   /* [offset: 12] reserved */
    uint8_t direction;      /* [offset: 13] 加密方向。 */
    uint8_t reserved2[6];   /* [offset: 14] reserved */
    uint32_t key_handle;    /* [offset: 20] 用于操作的密钥，当key_type为0时有效。 */
    uint8_t reserved3[12];  /* [offset: 24] reserved */
    raddr_t input_addr;     /* [offset: 36] 输入数据的地址。 */
    uint32_t input_size;    /* [offset: 44] 输入数据的长度。 */
    raddr_t output_addr;    /* [offset: 48] 输出数据的地址。 */
    uint32_t output_size;   /* [offset: 56] 输出缓冲区的长度。 */
    raddr_t plain_key_addr; /* [offset: 60] 明文密钥，key_type为1时有效。 */
} mb_cmd_rsa_cipher_st;

/* response struct */
typedef struct {
    uint32_t ret_code;    /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t output_size; /* [offset: 4] 输出明文或密文的大小。 */
} mb_rsp_rsa_cipher_st;

/* ---- command Rsa_cipher end ---- */

/* ---- command Rsa_sign start ---- */

#define MB_CMD_ID_RSA_SIGN 0x0502U /* Command ID for Rsa_sign*/

#define MB_RSA_SIGN_RSA_PADDING_TYPE_NONE       0x00U /* 不填充 */
#define MB_RSA_SIGN_RSA_PADDING_TYPE_RSASSA_PSS 0x01U /* RSASSA PSS 填充 */
#define MB_RSA_SIGN_ALGORITHM_SHA256            0x02U /*  */
#define MB_RSA_SIGN_ALGORITHM_SHA384            0x03U /*  */
#define MB_RSA_SIGN_ALGORITHM_SHA512            0x04U /*  */
#define MB_RSA_SIGN_ALGORITHM_SHA1              0x05U /*  */
#define MB_RSA_SIGN_ALGORITHM_SHA224            0x06U /*  */
#define MB_RSA_SIGN_ALGORITHM_SHA512_224        0x07U /*  */
#define MB_RSA_SIGN_ALGORITHM_SHA512_256        0x08U /*  */

/* struct Rsa_sign, RSA 签名/验证命令。 */
typedef struct {
    uint16_t cmd_id;          /* [offset: 0] 0x0502 */
    uint16_t cmd_id_inv;      /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];     /* [offset: 4] reserved */
    uint8_t key_type;         /* [offset: 11] 密钥类型 */
    uint8_t process_mode;     /* [offset: 12] 处理模式。 */
    uint8_t direction;        /* [offset: 13] 签名方向。 */
    uint8_t rsa_padding_type; /* [offset: 14] RSA 填充类型。 */
    uint8_t algorithm;        /* [offset: 15] 用于签名或验证的哈希算法。 */
    uint8_t reserved1[3];     /* [offset: 16] reserved */
    uint8_t msg_type;         /* [offset: 14] 表示msg_addr地址指向的数据类型. 0x00:完整消息,
                                 0x01:消息摘要，仅支持process_mode为ONEPASS */
    uint32_t key_handle;      /* [offset: 20] 用于操作的密钥。 */
    uint8_t reserved2[12];    /* [offset: 24] reserved */
    raddr_t msg_addr;         /* [offset: 36] 输入消息的地址。 */
    uint32_t msg_size;        /* [offset: 44] 输入消息的长度。 */
    raddr_t sign_addr;        /* [offset: 48] 签名数据的地址。 */
    uint32_t sign_size;       /* [offset: 56] 生成的签名缓冲区的长度或待验证的签名值长度。 */
    uint8_t reserved3[8];     /* [offset: 60] reserved */
    uint32_t salt_size;       /* [offset: 68] 盐值的长度，将用于 RSASSA PSS 填充。 */
    raddr_t sign_ctx;         /* [offset: 72] 签名或验证的上下文地址。 */
    uint32_t sign_ctx_size;   /* [offset: 80] 上下文的长度。 */
    raddr_t plain_key_addr;   /* [offset: 84] 明文密钥，key_type为1时有效。 */
} mb_cmd_rsa_sign_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t sign_size;    /* [offset: 4] 输出签名的大小。验证服务中忽略。 */
    uint32_t verification; /* [offset: 8] 验证结果。0 表示成功，其他表示失败。签名服务中忽略。 */
} mb_rsp_rsa_sign_st;

/* ---- command Rsa_sign end ---- */

/* ---- command Ecdsa start ---- */

#define MB_CMD_ID_ECDSA 0x0601U /* Command ID for Ecdsa*/

#define MB_ECDSA_ALGORITHM_SM3        0x00U /*  */
#define MB_ECDSA_ALGORITHM_MD5        0x01U /*  */
#define MB_ECDSA_ALGORITHM_SHA256     0x02U /*  */
#define MB_ECDSA_ALGORITHM_SHA384     0x03U /*  */
#define MB_ECDSA_ALGORITHM_SHA512     0x04U /*  */
#define MB_ECDSA_ALGORITHM_SHA1       0x05U /*  */
#define MB_ECDSA_ALGORITHM_SHA224     0x06U /*  */
#define MB_ECDSA_ALGORITHM_SHA512_224 0x07U /*  */
#define MB_ECDSA_ALGORITHM_SHA512_256 0x08U /*  */
#define MB_ECDSA_ALGORITHM_SHA3_224   0x09U /*  */
#define MB_ECDSA_ALGORITHM_SHA3_256   0x0aU /*  */
#define MB_ECDSA_ALGORITHM_SHA3_384   0x0bU /*  */
#define MB_ECDSA_ALGORITHM_SHA3_512   0x0cU /*  */

/* struct ecc_key, ECC明文密钥数据结构 */
typedef struct {
    uint32_t curve_id; /* [offset: 0] ECC曲线编号 */
    raddr_t privkey;   /* [offset: 4] ECC私钥的存储地址的地址，长度由curve_id对应的曲线类型决定。 */
    raddr_t pubkey;    /* [offset: 12] ECC公钥的存储地址的地址，长度由curve_id对应的曲线类型决定。 */
} mb_ecc_key_st;

/* struct Ecdsa, ECDSA 签名/验证命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0x0601 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7];   /* [offset: 4] reserved */
    uint8_t key_type;       /* [offset: 11] 密钥类型 */
    uint8_t process_mode;   /* [offset: 12] 处理模式。 */
    uint8_t direction;      /* [offset: 13] 签名方向。 */
    uint8_t reserved1[1];   /* [offset: 14] reserved */
    uint8_t algorithm;      /* [offset: 15] 签名/验证所使用的HASH算法。 */
    uint8_t reserved2[3];   /* [offset: 16] reserved */
    uint8_t msg_type;       /* [offset: 14] 表示msg_addr地址指向的数据类型. 0x00:完整消息,
                               0x01:消息摘要，仅支持process_mode为ONEPASS */
    uint32_t key_handle;    /* [offset: 20] 用于操作的密钥。 */
    uint8_t reserved3[12];  /* [offset: 24] reserved */
    raddr_t msg_addr;       /* [offset: 36] 输入消息的地址。 */
    uint32_t msg_size;      /* [offset: 44] 输入消息的长度。 */
    raddr_t sign_addr;      /* [offset: 48] 签名数据的地址。 */
    uint32_t sign_size;     /* [offset: 56] 生成的签名缓冲区的长度或待验证的签名值长度。 */
    uint8_t reserved4[12];  /* [offset: 60] reserved */
    raddr_t sign_ctx;       /* [offset: 72] 签名或验证的上下文地址。 */
    uint32_t sign_ctx_size; /* [offset: 80] 上下文的长度。 */
    raddr_t plain_key_addr; /* [offset: 84] 明文密钥，key_type为1时有效。 */
} mb_cmd_ecdsa_st;

/* response struct */
typedef struct {
    uint32_t ret_code;     /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t sign_size;    /* [offset: 4] 输出签名的大小。验证时忽略。 */
    uint32_t verification; /* [offset: 8] 验证结果。0 表示成功，其他表示失败。签名服务中忽略。 */
} mb_rsp_ecdsa_st;

/* ---- command Ecdsa end ---- */

/* ---- command sm9_cipher start ---- */

#define MB_CMD_ID_SM9_CIPHER 0x0701U /* Command ID for sm9_cipher*/

/* struct sm9_cipher, SM9 加解密命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0701 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7]; /* [offset: 4] reserved */
    uint8_t key_type;     /* [offset: 11] 密钥类型 */
    uint8_t enc_type;     /* [offset: 12] SM9 的内部加密模式。 */
    uint8_t direction;    /* [offset: 13] 加密方向。 */
    uint8_t padding_type; /* [offset: 14] 填充模式，仅在 enc_type 为 `SM9-ENC-TYPE-SM4` 时有效 */
    uint8_t key2_size;    /* [offset: 15] 内部 MAC 算法密钥的字节长度。 */
    uint8_t reserved1[2]; /* [offset: 16] reserved */
    uint8_t hid;          /* [offset: 18] 私钥生成函数标识符，由 KGC 选择并披露。 */
    uint8_t reserved2[1]; /* [offset: 19] reserved */
    uint32_t key_handle;  /* [offset: 20] SM9 密钥的句柄，用于加密，，当key_type为0时有效。 */
    raddr_t kgc_pub_key;  /* [offset: 24] KGC master公钥的地址，此公钥大小为 64 字节。解密模式中忽略。 */
    uint8_t reserved3[4]; /* [offset: 32] reserved */
    raddr_t input_addr;   /* [offset: 36] 输入数据的地址。 */
    uint32_t input_size;  /* [offset: 44] 输入数据的字节数，必须小于 1024。 */
    raddr_t output_addr;  /* [offset: 48] 输出数据的地址。 */
    uint32_t output_size; /* [offset: 56] 输出数据缓部区的长度。 */
    raddr_t id_addr;      /* [offset: 60] 用户 ID 的地址。 */
    uint32_t id_size;     /* [offset: 68] 加密接收方用户 ID 的大小，最大为 1024 字节。 */
    raddr_t fp12g; /* [offset: 72] e(P1, pub_key) 的值的地址，如果设置为 NULL，将在 eHSM 中计算，fp12g 的大小为 384
                      字节。 */
    raddr_t plain_key_addr; /* [offset: 80] 明文密钥，key_type为1时有效。 */
} mb_cmd_sm9_cipher_st;

/* response struct */
typedef struct {
    uint32_t ret_code;    /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t output_size; /* [offset: 4] 输出明文或密文的大小 */
} mb_rsp_sm9_cipher_st;

/* ---- command sm9_cipher end ---- */

/* ---- command sm9_sign start ---- */

#define MB_CMD_ID_SM9_SIGN 0x0702U /* Command ID for sm9_sign*/

/* struct sm9_sign_value_struct, SM9 签名值结构。 */
typedef struct {
    uint8_t h[32]; /* [offset: 0] SM9 签名值中的 h 值。 */
    uint8_t s[65]; /* [offset: 32] SM9 签名值中的 s 值。 */
} mb_sm9_sign_value_struct_st;

/* struct sm9_sign, SM9 签名/验证命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0702 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[7]; /* [offset: 4] reserved */
    uint8_t key_type;     /* [offset: 11] 密钥类型 */
    uint8_t reserved1[1]; /* [offset: 12] reserved */
    uint8_t direction;    /* [offset: 13] 签名方向。 */
    uint8_t reserved2[4]; /* [offset: 14] reserved */
    uint8_t hid;          /* [offset: 18] 私钥生成函数标识符，由 KGC 选择并披露。 */
    uint8_t reserved3[1]; /* [offset: 19] reserved */
    uint32_t key_handle;  /* [offset: 20] SM9 密钥的句柄，当key_type为0时有效。 */
    raddr_t kgc_pub_key;  /* [offset: 24] KGC master公钥的地址，此公钥大小为 128 字节。 */
    uint8_t reserved4[4]; /* [offset: 32] reserved */
    raddr_t msg_addr;     /* [offset: 36] 输入消息的地址。 */
    uint32_t msg_size;    /* [offset: 44] 输入消息的字节数，必须小于 1024。 */
    raddr_t sign_addr;    /* [offset: 48] 签名值的地址。 */
    uint32_t sign_size;   /* [offset: 56] 签名缓冲区或签名值的大小。 */
    raddr_t id_addr;      /* [offset: 60] 用户 ID 的地址。 */
    uint32_t id_size;     /* [offset: 68] 用户 ID 的大小，最大为 1024 字节。 */
    raddr_t fp12g; /* [offset: 72] e(P1, pub_key) 的值的地址，如果设置为 NULL，将在 eHSM 中计算，fp12g 的大小为 384
                      字节。 */
    raddr_t plain_key_addr; /* [offset: 80] 明文密钥，key_type为1时有效。 */
} mb_cmd_sm9_sign_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_sm9_sign_st;

/* ---- command sm9_sign end ---- */

/* ---- group 随机数生成 ---- */
/* 提供随机数生成相关的命令。  */

/* ---- command rng start ---- */

#define MB_CMD_ID_RNG 0x0a01U /* Command ID for rng*/

#define MB_RNG_ALGORITHM_SM4_CTRDRBG 0x00U /* SM4 CTRDRBG */
#define MB_RNG_ALGORITHM_AES_CTRDRBG 0x01U /* AES CTRDRBG */

/* struct rng, 随机数生成命令。 */
typedef struct {
    uint16_t cmd_id;          /* [offset: 0] 0x0a01 */
    uint16_t cmd_id_inv;      /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[11];    /* [offset: 4] reserved */
    uint8_t algorithm;        /* [offset: 15] 随机数后处理算法。 */
    uint8_t reserved1[32];    /* [offset: 16] reserved */
    raddr_t random_data_addr; /* [offset: 48] 生成的随机数据地址。 */
    uint32_t require_size;    /* [offset: 56] 生成的随机数据大小。 */
} mb_cmd_rng_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_rng_st;

/* ---- command rng end ---- */

/* ---- group 扩展服务 ---- */
/* 一些额外的功能服务命令。  */

/* ---- command otp_write start ---- */

#define MB_CMD_ID_OTP_WRITE 0xff01U /* Command ID for otp_write*/

/* struct otp_write,
 * 固件中的OTP数据写入命令。此命令可用于写入生命周期、UID、控制字段、传感器响应配置和系统密钥等数据。此命令只能在TEST_MODE和DEVELOP_MODE模式下执行。
 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff01 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t
        ehsm_dst_addr;     /* [offset: 12]
                              eHSM内部地址，数据将写入到该地址。调用者应非常小心该值和写入内容，因为OTP存储只能写入一次。固件不会检查此值的有效性。
                            */
    uint32_t size;         /* [offset: 20] 要写入的数据的字节大小。 */
    raddr_t host_src_addr; /* [offset: 24] host地址，待写入OTP的数据从该host地址读取。 */
} mb_cmd_otp_write_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_otp_write_st;

/* ---- command otp_write end ---- */

/* ---- command otp_read start ---- */

#define MB_CMD_ID_OTP_READ 0xff02U /* Command ID for otp_read*/

/* struct otp_read,
 * 固件中的OTP数据读取命令。此命令可用于读取生命周期、UID、控制字段、传感器响应配置和系统密钥等数据。此命令只能在TEST_MODE和DEVELOP_MODE模式下执行。
 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff02 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_src_addr; /* [offset: 12] eHSM地址，OTP数据将从该地址读取。 */
    uint32_t size;         /* [offset: 20] 要读取的数据的字节大小。固件不会检查此值的有效性。 */
    raddr_t host_dst_addr; /* [offset: 24] host地址，读取到的OTP数据将被拷贝到HOST的地址。 */
} mb_cmd_otp_read_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_otp_read_st;

/* ---- command otp_read end ---- */

/* ---- command get_challenge start ---- */

#define MB_CMD_ID_GET_CHALLENGE 0xff03U /* Command ID for get_challenge*/

/* struct get_challenge, 获取挑战值命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff03 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t type;          /* [offset: 12] 获取挑战的类型。 */
    uint8_t reserved1[35]; /* [offset: 13] reserved */
    raddr_t addr;          /* [offset: 48] host地址，用于存储挑战数据。 */
} mb_cmd_get_challenge_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_get_challenge_st;

/* ---- command get_challenge end ---- */

/* ---- command debug_auth start ---- */

#define MB_CMD_ID_DEBUG_AUTH 0xff04U /* Command ID for debug_auth*/

#define MB_DEBUG_AUTH_ALG_SM2_WITH_SM3             0x01U /* SM3-SM2 */
#define MB_DEBUG_AUTH_ALG_ECCSECP256R1_WITH_SHA256 0x02U /* SHA256-SECP256R1 */
#define MB_DEBUG_AUTH_ALG_SM4_CMAC                 0x03U /* SM4-CMAC */
#define MB_DEBUG_AUTH_ALG_AES128_CMAC              0x04U /* AES128-CMAC */
#define MB_DEBUG_AUTH_ALG_SHA256_RSA               0x05U /* SHA256_RSA */

/* struct debug_auth, 调试身份验证命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff04 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t type;          /* [offset: 12] 之前获取的挑战类型。 */
    uint8_t alg;           /* [offset: 13] 用于验证的算法。 */
    uint8_t reserved1[10]; /* [offset: 14] reserved */
    raddr_t sign_addr;     /* [offset: 24] 签名值的host地址。 */
    uint32_t sign_size;    /* [offset: 32] 签名的字节大小。 */
    raddr_t pub_addr;      /* [offset: 36] 用于验证的公钥的host地址。 */
    uint32_t pub_size;     /* [offset: 44] 签名者公钥的字节大小。 */
    raddr_t
        soc_dbg_bitmap_addr;      /* [offset: 48]
                                     SOC调试身份验证位图数据的host地址。仅对于SOC调试身份验证有效。大小为5个字。前4个字表示每个位是否打开相应的硬件调试端口（为1的位表示打开对应端口，为0的位表示不改变对应端口状态）。最后一个字只有最低位有效（表示是否启用硬件调试端口的129位）。
                                   */
    uint32_t soc_dbg_bitmap_size; /* [offset: 56] SOC调试身份验证位图数据的大小。固定长度（5个字）。 */
} mb_cmd_debug_auth_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_debug_auth_st;

/* ---- command debug_auth end ---- */

/* ---- command close_debug start ---- */

#define MB_CMD_ID_CLOSE_DEBUG 0xff0eU /* Command ID for close_debug*/

/* struct close_debug, 关闭调试命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff0e */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t type;         /* [offset: 12] 关闭调试的类型。 */
    uint8_t reserved1[3]; /* [offset: 13] reserved */
    raddr_t
        soc_dbg_bitmap_addr;      /* [offset: 16]
                                     SOC调试身份验证位图数据的host地址。仅对于SOC调试身份验证有效。大小为5个字。前4个字表示每个位是否关闭相应的硬件调试端口（为1的位表示关闭对应端口，为0的位表示不改变对应端口状态）。最后一个字只有最低位有效（表示是否关闭了硬件调试端口的129位）。
                                   */
    uint32_t soc_dbg_bitmap_size; /* [offset: 24] SOC调试身份验证位图数据的大小。固定长度（5个字）。 */
} mb_cmd_close_debug_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_close_debug_st;

/* ---- command close_debug end ---- */

/* ---- command fw_upgrade start ---- */

#define MB_CMD_ID_FW_UPGRADE 0xff05U /* Command ID for fw_upgrade*/

/* struct fw_upgrade, 固件镜像升级命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff05 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t process_mode;  /* [offset: 12] 处理模式。 */
    uint8_t reserved1[19]; /* [offset: 13] reserved */
    raddr_t image_addr;    /* [offset: 32] 镜像地址。 */
    uint32_t image_size;   /* [offset: 40] 升级镜像的大小（以字节为单位）。 */
    raddr_t storage_addr;  /* [offset: 44] 输出的启动镜像的host地址。 */
} mb_cmd_fw_upgrade_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_fw_upgrade_st;

/* ---- command fw_upgrade end ---- */

/* ---- command soc_verify start ---- */

#define MB_CMD_ID_SOC_VERIFY 0xff06U /* Command ID for soc_verify*/

#define MB_SOC_VERIFY_CHECK_VERSION_OFF 0x00U /* 不检查版本计数器 */
#define MB_SOC_VERIFY_CHECK_VERSION_ON  0x01U /* 需要检查版本计数器 */

/* struct soc_verify, 验证SOC启动镜像命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0xff06 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[10];  /* [offset: 4] reserved */
    uint8_t check_version;  /* [offset: 14] 是否检查版本计数器。 */
    uint8_t reserved1[1];   /* [offset: 15] reserved */
    raddr_t image_addr;     /* [offset: 16] 镜像的host地址。 */
    uint32_t image_size;    /* [offset: 24] 镜像的大小（以字节为单位）。 */
    raddr_t image_out_addr; /* [offset: 28] 解密后的镜像（或如果镜像为明文则进行复制）存储的host地址。 */
} mb_cmd_soc_verify_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_soc_verify_st;

/* ---- command soc_verify end ---- */

/* ---- command install_random_key start ---- */

#define MB_CMD_ID_INSTALL_RANDOM_KEY 0xff08U /* Command ID for install_random_key*/

#define MB_INSTALL_RANDOM_KEY_KEY_LEVEL_1                    0x02U /* 随机密钥使用CHIP_ROOT_KEY加密。 */
#define MB_INSTALL_RANDOM_KEY_KEY_LEVEL_2                    0x04U /* 随机密钥使用DEVICE_ROOT_KEY加密。 */
#define MB_INSTALL_RANDOM_KEY_KEY_TYPE_SYMMETRIC_KEY         0x01U /* 用于对称密钥 */
#define MB_INSTALL_RANDOM_KEY_KEY_TYPE_SM2_PRIVATE_KEY       0x02U /* 用于SM2私钥 */
#define MB_INSTALL_RANDOM_KEY_KEY_TYPE_SECP256R1_PRIVATE_KEY 0x04U /* 用于secp256r1私钥 */

/* struct install_random_key, 安装随机密钥命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff08 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t key_level;     /* [offset: 12] 安装的OTP密钥级别 */
    uint8_t key_type;      /* [offset: 13] 密钥类型。 */
    uint16_t key_slot_id;  /* [offset: 14]
                              指示密钥安装到eHSM的哪个硬件槽位ID（OTP中的密钥索引），可用的ID范围请参考OTP密钥章节。 */
    uint8_t key_last_flag; /* [offset: 16] 指示安装的密钥是否为最后一个密钥。 */
    uint8_t reserved1[3];  /* [offset: 17] reserved */
} mb_cmd_install_random_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_install_random_key_st;

/* ---- command install_random_key end ---- */

/* ---- command install_encrypt_key start ---- */

#define MB_CMD_ID_INSTALL_ENCRYPT_KEY 0xff09U /* Command ID for install_encrypt_key*/

#define MB_INSTALL_ENCRYPT_KEY_KEY_LEVEL_1                        0x02U /* 加密密钥使用CHIP_ROOT_KEY加密。 */
#define MB_INSTALL_ENCRYPT_KEY_KEY_LEVEL_2                        0x04U /* 加密密钥使用DEVICE_ROOT_KEY加密。 */
#define MB_INSTALL_ENCRYPT_KEY_KEY_TYPE_SYMMETRIC_KEY             0x01U /* 用于对称密钥 */
#define MB_INSTALL_ENCRYPT_KEY_KEY_TYPE_SM2_SECP256R1_PRIVATE_KEY 0x02U /* 用于SM2/SECP256R1私钥 */
#define MB_INSTALL_ENCRYPT_KEY_KEY_TYPE_HASH_PUBLIC_KEY           0x04U /* 用于公钥的哈希值 */

/* struct install_encrypt_key, 安装加密密钥命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff09 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t key_level;    /* [offset: 12] eHSM或SOC密钥级别。 */
    uint8_t key_type;     /* [offset: 13] 密钥类型。 */
    uint16_t
        key_slot_id;       /* [offset: 14]
                              指示密钥安装到eHSM的哪个硬件槽位ID（OTP中的密钥索引），可用的ID范围请参考OTP密钥章节，最小为3。
                            */
    uint8_t key_last_flag; /* [offset: 16] 指示安装的密钥是否为最后一个密钥。 */
    uint8_t reserved1[19]; /* [offset: 17] reserved */
    raddr_t input_addr;    /* [offset: 36] 输入密钥或HASH值的host地址。32字节密钥（或哈希）+
                              4字节密钥（或哈希）的CRC值，用0x00填充至48字节，并使用RTL（eHSM/SOC）KEK加密的结果。 */
    uint32_t input_size;   /* [offset: 44] 输入密钥或HASH值的大小，长度固定为48字节。 */
} mb_cmd_install_encrypt_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_install_encrypt_key_st;

/* ---- command install_encrypt_key end ---- */

/* ---- command she_get_status start ---- */

#define MB_CMD_ID_SHE_GET_STATUS 0x0040U /* Command ID for she_get_status*/

/* struct she_get_status, 获取SHE状态命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0040 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
} mb_cmd_she_get_status_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t she_status; /* [offset: 4] SHE状态的值，仅最低字节有效。 */
} mb_rsp_she_get_status_st;

/* ---- command she_get_status end ---- */

/* ---- command she_get_id start ---- */

#define MB_CMD_ID_SHE_GET_ID 0x0060U /* Command ID for she_get_id*/

/* struct she_get_id, 获取SHE ID命令。 */
typedef struct {
    uint16_t cmd_id;         /* [offset: 0] 0x0060 */
    uint16_t cmd_id_inv;     /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];    /* [offset: 4] reserved */
    raddr_t challenge;       /* [offset: 12] 用户设置的挑战值。 */
    uint32_t challenge_size; /* [offset: 20] 挑战值的大小。 */
    raddr_t status;          /* [offset: 24] UID和状态寄存器的输出缓冲区。 */
    uint32_t status_size;    /* [offset: 32] 状态的大小。初始化为缓冲区大小。必须不小于16。 */
    raddr_t sign;            /* [offset: 36] 签名的输出缓冲区。 */
    uint32_t sign_size;      /* [offset: 44] 签名的大小。初始化为缓冲区大小。必须不小于16。 */
} mb_cmd_she_get_id_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_she_get_id_st;

/* ---- command she_get_id end ---- */

/* ---- command get_emu start ---- */

#define MB_CMD_ID_GET_EMU 0x0070U /* Command ID for get_emu*/

/* struct ehsm_emu_status, 用于获取 eHSM EMU 状态信息的数据结构。 */
typedef struct {
    uint32_t o_hsm_status[2];  /* [offset: 0] eHSM 状态 */
    uint32_t o_hsm_err_sensor; /* [offset: 8] 传感器检测到的错误 */
    uint32_t o_hsm_err_hw[2];  /* [offset: 12] 硬件检测到的错误 */
    uint32_t o_hsm_err_fw[2];  /* [offset: 20] 固件检测到的错误 */
} mb_ehsm_emu_status_st;

/* struct get_emu, 获取EMU状态命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0x0070 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[36]; /* [offset: 4] reserved */
    raddr_t emu_addr;      /* [offset: 40] EMU状态的输出缓冲区。 */
    uint32_t emu_size;     /* [offset: 48] emu_addr的缓冲区大小。 */
} mb_cmd_get_emu_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t emu_size; /* [offset: 4] EMU状态的输出大小。仅在命令成功时有效。 */
} mb_rsp_get_emu_st;

/* ---- command get_emu end ---- */

/* ---- command change_lifecycle start ---- */

#define MB_CMD_ID_CHANGE_LIFECYCLE 0x0f01U /* Command ID for change_lifecycle*/

/* struct change_lifecycle, 更改生命周期状态命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0f01 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
    uint32_t type;       /* [offset: 4] 生命周期类型。 */
} mb_cmd_change_lifecycle_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_change_lifecycle_st;

/* ---- command change_lifecycle end ---- */

/* ---- command change_control_field start ---- */

#define MB_CMD_ID_CHANGE_CONTROL_FIELD 0x0f02U /* Command ID for change_control_field*/

/* struct change_control_field, 更改控制字段命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0f02 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t type;         /* [offset: 4] 控制字段类型。 */
    uint8_t reserved0[1]; /* [offset: 5] reserved */
    uint16_t size;        /* [offset: 6] 值的大小，此值固定为8，即2个word，请参考TRM文档。 */
    raddr_t value;        /* [offset: 8] 要更新的值的地址。 */
} mb_cmd_change_control_field_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_change_control_field_st;

/* ---- command change_control_field end ---- */

/* ---- command set_uart_baudrate start ---- */

#define MB_CMD_ID_SET_UART_BAUDRATE 0x0f04U /* Command ID for set_uart_baudrate*/

/* struct set_uart_baudrate, 设置UART波特率命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0f04 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
    uint32_t baud_div;   /* [offset: 4] UART的分频值，指CPU频率值除以UART波特率值所得的结果。 */
} mb_cmd_set_uart_baudrate_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_set_uart_baudrate_st;

/* ---- command set_uart_baudrate end ---- */

/* ---- command fw_reg_wr start ---- */

#define MB_CMD_ID_FW_REG_WR 0xff23U /* Command ID for fw_reg_wr*/

/* struct fw_reg_wr, CFG数据写入命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff23 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_dst_addr; /* [offset: 12] eHSM地址，数据将写入此地址。 */
    uint32_t size;         /* [offset: 20] 要写入的数据的字节大小。 */
    raddr_t host_src_addr; /* [offset: 24] host地址，数据将从此地址读取。 */
} mb_cmd_fw_reg_wr_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_fw_reg_wr_st;

/* ---- command fw_reg_wr end ---- */

/* ---- command fw_reg_rd start ---- */

#define MB_CMD_ID_FW_REG_RD 0xff24U /* Command ID for fw_reg_rd*/

/* struct fw_reg_rd, CFG数据读取命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0xff24 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    raddr_t ehsm_src_addr; /* [offset: 12] eHSM地址，数据将从此地址读取。 */
    uint32_t size;         /* [offset: 20] 要读取的数据的字节大小。固件无需验证此值的有效性。 */
    raddr_t host_dst_addr; /* [offset: 24] host地址，数据将写入此地址。缓冲区应具有足够的大小。 */
} mb_cmd_fw_reg_rd_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_fw_reg_rd_st;

/* ---- command fw_reg_rd end ---- */

/* ---- command ehsm_read_ver start ---- */

#define MB_CMD_ID_EHSM_READ_VER 0xff10U /* Command ID for ehsm_read_ver*/

/* struct ehsm_version, 用于获取 eHSM 版本信息的数据结构 */
typedef struct {
    uint8_t type;      /* [offset: 0] 固件类型 */
    uint8_t ver_major; /* [offset: 1] 主版本号。 */
    uint8_t ver_minor; /* [offset: 2] 次版本号。 */
    uint8_t ver_patch; /* [offset: 3] 补丁版本号。 */
    uint8_t
        ver_pre_release[8];  /* [offset: 4] 预发布版本字符串，例如 `alpha.1`，`rc3`。对于正式版本，这是一个空字符串。 */
    uint8_t reserved0[8];    /* [offset: 12] reserved */
    uint32_t pke_engine_ver; /* [offset: 20] PKE 引擎版本号。 */
    uint32_t pke_lib_ver;    /* [offset: 24] PKE 库版本号。格式: 0x23080301 表示 2023-08-03 版本 1。 */
    uint32_t ske_engine_ver; /* [offset: 28] SKE 引擎版本号。 */
    uint32_t ske_lib_ver;    /* [offset: 32] SKE 库版本号。格式: 同 pke_lib_ver。 */
    uint32_t hash_engine_ver; /* [offset: 36] HASH 引擎版本号。 */
    uint32_t hash_lib_ver;    /* [offset: 40] HASH 库版本号。格式: 同 pke_lib_ver。 */
    uint32_t trng_engine_ver; /* [offset: 44] TRNG 引擎版本号。 */
    uint32_t trng_lib_ver;    /* [offset: 48] TRNG 库版本号。格式: 同 pke_lib_ver。 */
    uint32_t hw_ver;          /* [offset: 52] 硬件版本号，参见 OSR_eHSM_FuSa_TRM_vxxx.pdf 中的 SYS_VER1。 */
    uint8_t uid[16];          /* [offset: 56] 从 OTP 读取的 16 字节 UID 值。 */
    uint8_t reserved1[56];    /* [offset: 72] reserved */
} mb_ehsm_version_st;

/* struct ehsm_read_ver, 读取固件版本命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0xff10 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t ver_addr;     /* [offset: 12] 版本信息的host地址。 */
    uint32_t ver_size;    /* [offset: 20] 版本缓冲区的大小 */
} mb_cmd_ehsm_read_ver_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_ehsm_read_ver_st;

/* ---- command ehsm_read_ver end ---- */


/* ---- command enter_wfi start ---- */

#define MB_CMD_ID_ENTER_WFI 0xff26U /* Command ID for enter_wfi*/

/* struct enter_wfi, 进入WFI（节能）模式命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0xff26 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
} mb_cmd_enter_wfi_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_enter_wfi_st;

/* ---- command enter_wfi end ---- */

/* ---- group 密钥管理 ---- */
/* 密钥管理相关的命令，包含密钥的生成、导入、导出、删除等。  */

/* ---- command ehsm_gen_key start ---- */

#define MB_CMD_ID_EHSM_GEN_KEY 0x080dU /* Command ID for ehsm_gen_key*/

/* struct ehsm_gen_key, 生成对称和非对称密钥命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x080d */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t algo_id;      /* [offset: 12] 生成密钥的算法ID。 */
    uint8_t reserved1[3]; /* [offset: 13] reserved */
    uint16_t
        rsa_e_bit_size;   /* [offset: 16]
                             RSA公钥e的位长度。最大为64。当公钥的位长度为17时，输出的公钥e值固定为65537（0x10001）。仅对生成RSA密钥有效。
                           */
    uint16_t key_size;    /* [offset: 18] 创建密钥的长度。仅对生成HMAC密钥有效，最大长度为512字节。 */
    uint32_t key_handle;  /* [offset: 20] 生成密钥的密钥句柄，设置为0xFFFFFFFF表示由密钥管理服务分配的句柄。 */
    uint32_t permit;      /* [offset: 24] 生成的新密钥的权限值。密钥可以有多个权限。 */
    uint8_t reserved2[4]; /* [offset: 28] reserved */
    raddr_t
        dh_common_addr;      /* [offset: 32] DH公共数据的地址。其数据格式为{p_len + p_value + q_len + q_value + g_len +
                                g_value + h_len +
                                h_value}。x_len的值表示x_value值的长度。h_value是可选的，将h_len的值设置为0表示h_value不存在。x_len的长度为4字节。仅对生成DH密钥有效。
                              */
    uint32_t dh_common_size; /* [offset: 40] DH公共数据的长度。仅对生成DH密钥有效，最大长度为2064字节。 */
} mb_cmd_ehsm_gen_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_handle; /* [offset: 4] 返回的密钥句柄。 */
} mb_rsp_ehsm_gen_key_st;

/* ---- command ehsm_gen_key end ---- */

/* ---- command ehsm_key_derive start ---- */

#define MB_CMD_ID_EHSM_KEY_DERIVE 0x080eU /* Command ID for ehsm_key_derive*/

#define MB_EHSM_KEY_DERIVE_KEY_DERIV_FUNC_KDFX963                    0x01U /* KDFX963算法 */
#define MB_EHSM_KEY_DERIVE_KEY_DERIV_FUNC_PBKDF2                     0x02U /* PBKDF2算法 */
#define MB_EHSM_KEY_DERIVE_DERIVE_TYPE_KMS_KEY_DERIVE_USER_PASSWD    0x01U /* 使用用户密码派生密钥 */
#define MB_EHSM_KEY_DERIVE_DERIVE_TYPE_KMS_KEY_DERIVE_USER_KEYHANDLE 0x02U /* 使用用户父密钥派生密钥 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SM3                              0x00U /* SM3算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_MD5                              0x01U /* MD5算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA256                           0x02U /* SHA-256算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA384                           0x03U /* SHA-384算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA512                           0x04U /* SHA-512算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA1                             0x05U /* SHA-1算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA224                           0x06U /* SHA-224算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA512_224                       0x07U /* SHA-512/224算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA512_256                       0x08U /* SHA-512/256算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA3_224                         0x09U /* SHA3-224算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA3_256                         0x0aU /* SHA3-256算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA3_384                         0x0bU /* SHA3-384算法 */
#define MB_EHSM_KEY_DERIVE_HASH_ALG_SHA3_512                         0x0cU /* SHA3-512算法 */
#define MB_EHSM_KEY_DERIVE_KEY_OUT_DIR_KEY_DERIVE_OUTPUT_TO_KMS      0x01U /* 密钥将存储在eHSM KMS中 */
#define MB_EHSM_KEY_DERIVE_KEY_OUT_DIR_KEY_DERIVE_OUTPUT_TO_SOC      0x02U /* 密钥将通过硬件安全通道输出到SOC */

/* struct ehsm_key_derive, 密钥派生命令。 */
typedef struct {
    uint16_t cmd_id;            /* [offset: 0] 0x080e */
    uint16_t cmd_id_inv;        /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];       /* [offset: 4] reserved */
    uint8_t key_deriv_func;     /* [offset: 12] 密钥派生的函数标识符。 */
    uint8_t reserved1[1];       /* [offset: 13] reserved */
    uint8_t derive_type;        /* [offset: 14] 密钥派生类型。 */
    uint8_t hash_alg;           /* [offset: 15] 密钥派生的哈希算法。 */
    uint8_t algo_id;            /* [offset: 16] 派生密钥的密钥算法ID。注意：仅对称密钥算法ID有效。 */
    uint8_t key_out_dir;        /* [offset: 17] 密钥输出方向。 */
    uint8_t soc_sp_id;          /* [offset: 18] 指示派生密钥数据输出到哪个SOC安全端口索引，当 key_out_dir 为
                                   KEY_DERIVE_OUTPUT_TO_SOC 时有效。 */
    uint8_t reserved2[1];       /* [offset: 19] reserved */
    uint32_t key_handle;        /* [offset: 20] 派生密钥的密钥句柄，如果已存在则覆盖。0xFFFFFFFF值表示自动分配句柄。 */
    uint32_t permit;            /* [offset: 24] 派生密钥的权限值。密钥可以有多个权限位组合。 */
    uint8_t reserved3[4];       /* [offset: 28] reserved */
    uint32_t parent_key_handle; /* [offset: 32] 密钥派生的父密钥，当derive_type为KMS_KEY_DERIVE_USER_PASSWD时忽略 */
    raddr_t salt_data_addr;     /* [offset: 36] 盐数据的host地址。 */
    uint32_t salt_data_size;    /* [offset: 44] 派生密钥的盐参数。最大长度为128字节。 */
    raddr_t pw_data_addr;  /* [offset: 48] 密码数据的host地址。当derive_type为KMS_KEY_DERIVE_USER_KEYHANDLE时忽略。 */
    uint32_t pw_data_size; /* [offset: 56] 派生密钥的密码参数。最大长度为128字节。 */
    uint8_t reserved4[20]; /* [offset: 60] reserved */
    uint32_t itera_times;  /* [offset: 80] 迭代次数，仅对PBKDF2有效，过低的迭代次数影响安全性。 */
    uint8_t reserved5[8];  /* [offset: 84] reserved */
    uint16_t
        key_size; /* [offset: 92]
                     派生密钥的字节大小。如果算法ID是HMAC密钥，则最大大小为512字节。其他算法ID必须设置为与算法要求相匹配。
                   */
} mb_cmd_ehsm_key_derive_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_handle; /* [offset: 4] 返回的密钥句柄。 */
} mb_rsp_ehsm_key_derive_st;

/* ---- command ehsm_key_derive end ---- */

/* ---- command ehsm_key_exchange start ---- */

#define MB_CMD_ID_EHSM_KEY_EXCHANGE 0x080fU /* Command ID for ehsm_key_exchange*/

#define MB_SM2_PARAM_STRUCT_SM2_ROLE_KMS_SM2_ROLE_SPONSOR   0x00U /*  */
#define MB_SM2_PARAM_STRUCT_SM2_ROLE_KMS_SM2_ROLE_RESPONSOR 0x01U /*  */

/* struct sm2_param_struct, SM2参数结构体。 */
typedef struct {
    uint8_t sm2_role;               /* [offset: 0] 密钥交换的SM2角色。 */
    uint8_t reserved0[3];           /* [offset: 1] reserved */
    uint32_t local_tmp_key_handle;  /* [offset: 4] SM2交换本地临时密钥的密钥句柄。 */
    raddr_t s1_s2_value_addr;       /* [offset: 8] SM2交换s1_s2值的host地址。 */
    raddr_t sa_sb_value_addr;       /* [offset: 16] SM2交换sa_sb值的host地址。 */
    raddr_t peer_temp_pubkey_addr;  /* [offset: 24] SM2交换对方临时公钥值的host地址。 */
    uint32_t peer_temp_pubkey_size; /* [offset: 32] 对方临时公钥的长度。 */
} mb_sm2_param_struct_st;

/* struct ehsm_key_exchange, 密钥交换命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x080f */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t algo_id;      /* [offset: 12] 密钥交换生成的密钥算法ID，仅对称密钥算法ID有效。 */
    uint8_t reserved1[1]; /* [offset: 13] reserved */
    uint8_t reserved2[4]; /* [offset: 14] reserved */
    uint16_t
        key_size;        /* [offset: 18]
                            生成的密钥的字节大小。如果算法ID是HMAC密钥，则最大大小为512字节。其他算法ID必须设置为与算法要求相匹配的大小。
                          */
    uint32_t key_handle; /* [offset: 20] 交换密钥的密钥句柄，如果已存在则会被覆盖。0xFFFFFFFF值表示自动分配的句柄。 */
    uint32_t permit;     /* [offset: 24] 交换密钥的权限值。密钥可以由多个权限组合而成。 */
    uint32_t local_key_handle; /* [offset: 28] 内部私钥的密钥句柄。 */
    raddr_t
        dh_commom_addr;      /* [offset: 32] DH公共数据的地址。其数据格式为{p_len + p_value + q_len + q_value + g_len +
                                g_value + h_len +
                                h_value}。x_len的值表示x_value的值的长度。h_value是可选的，将h_len的值设置为0表示h_value不存在。x_len的长度为4字节。仅对生成DH密钥有效。
                              */
    uint32_t dh_commom_size; /* [offset: 40] DH公共数据的长度。仅对生成DH密钥有效。最大大小为2064字节。 */
    raddr_t remote_pubkey_data;  /* [offset: 44] 远程公钥数据的host地址。 */
    uint32_t remote_pubkey_size; /* [offset: 52] 远程公钥的大小。最大大小为512字节。 */
    uint8_t reserved3[12];       /* [offset: 56] reserved */
    raddr_t sm2_param_addr;      /* [offset: 68] 指向SM2参数的host地址。 */
} mb_cmd_ehsm_key_exchange_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_handle; /* [offset: 4] 返回的密钥句柄。 */
} mb_rsp_ehsm_key_exchange_st;

/* ---- command ehsm_key_exchange end ---- */

/* ---- command ehsm_import_key start ---- */

#define MB_CMD_ID_EHSM_IMPORT_KEY 0x0801U /* Command ID for ehsm_import_key*/

/* struct ehsm_import_key, 密钥导入命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0801 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint8_t reserved1[8]; /* [offset: 12] reserved */
    uint32_t key_handle;  /* [offset: 20] 导入密钥的密钥句柄，如果已存在则会被覆盖。0xFFFFFFFF值表示自动分配句柄。 */
    uint32_t transport_key_handle;    /* [offset: 24]
                                         用于传输保护（加密）导入密钥的密钥句柄，如果为0xFFFFFFFF，表示明文导入。 */
    uint8_t reserved2[4];             /* [offset: 28] reserved */
    uint32_t authenticity_key_handle; /* [offset: 32]
                                         用于传输保护（验证）导入密钥的密钥句柄，如果为0xFFFFFFFF，表示不校验MAC。 */
    raddr_t key_data_addr;            /* [offset: 36] 导入密钥数据的地址。不同密钥的格式不同。 */
    uint32_t key_data_size;           /* [offset: 44] 导入密钥的长度。最大长度为2348字节。 */
    raddr_t key_signature_addr;       /* [offset: 48] 导入密钥签名数据的地址。 */
    uint32_t key_signature_size;      /* [offset: 56] 导入密钥签名数据的长度。最大长度为32字节。 */
} mb_cmd_ehsm_import_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_handle; /* [offset: 4] 返回的密钥句柄。 */
} mb_rsp_ehsm_import_key_st;

/* ---- command ehsm_import_key end ---- */

/* ---- command ehsm_export_key start ---- */

#define MB_CMD_ID_EHSM_EXPORT_KEY 0x0802U /* Command ID for ehsm_export_key*/

#define MB_EHSM_EXPORT_KEY_REQ_KEY_PART_KMS_KEY_PART_PUBKEY  0x01U /* 公钥部分 */
#define MB_EHSM_EXPORT_KEY_REQ_KEY_PART_KMS_KEY_PART_PRIVKEY 0x02U /* 私钥部分，或对称密钥 */
#define MB_EHSM_EXPORT_KEY_REQ_KEY_PART_KMS_KEY_PART_PAIRKEY 0x03U /* 密钥对 */

/* struct ehsm_export_key, 密钥导出命令 */
typedef struct {
    uint16_t cmd_id;                  /* [offset: 0] 0x0802 */
    uint16_t cmd_id_inv;              /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];             /* [offset: 4] reserved */
    uint8_t reserved1[4];             /* [offset: 12] reserved */
    uint8_t req_key_part;             /* [offset: 16] 要导出的密钥数据的部分。 */
    uint8_t reserved2[3];             /* [offset: 17] reserved */
    uint32_t key_handle;              /* [offset: 20] 要导出的密钥的密钥句柄。 */
    uint32_t transport_key_handle;    /* [offset: 24]
                                         用于传输保护（解密）导出密钥的密钥句柄，如果为0xFFFFFFFF，表示明文导出密钥。 */
    uint8_t reserved3[4];             /* [offset: 28] reserved */
    uint32_t authenticity_key_handle; /* [offset: 32]
                                         用于传输保护（签名）导出密钥的密钥句柄，如果为0xFFFFFFFF，表示不生成MAC。 */
    raddr_t key_data_addr;            /* [offset: 36] 存储导出密钥数据的host地址。不同密钥的格式和长度不同。 */
    uint32_t key_data_size;           /* [offset: 44] 导出密钥数据缓冲的长度。 */
    raddr_t key_signature_addr;       /* [offset: 48] 存储导出密钥签名数据的host地址。 */
    uint32_t key_signature_size;      /* [offset: 56] 导出密钥签名数据的长度。 */
} mb_cmd_ehsm_export_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code;           /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_data_size;      /* [offset: 4] 返回的导出密钥数据的实际长度。 */
    uint32_t key_signature_size; /* [offset: 8] 返回的导出密钥签名数据（MAC）的实际长度。 */
} mb_rsp_ehsm_export_key_st;

/* ---- command ehsm_export_key end ---- */

/* ---- command ehsm_remove_key start ---- */

#define MB_CMD_ID_EHSM_REMOVE_KEY 0x0806U /* Command ID for ehsm_remove_key*/

/* struct ehsm_remove_key, 移除密钥命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0806 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint32_t key_handle;  /* [offset: 12] 要移除的密钥的密钥句柄。 */
} mb_cmd_ehsm_remove_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_ehsm_remove_key_st;

/* ---- command ehsm_remove_key end ---- */

/* ---- command ehsm_get_pub_from_priv start ---- */

#define MB_CMD_ID_EHSM_GET_PUB_FROM_PRIV 0x0805U /* Command ID for ehsm_get_pub_from_priv*/

/* struct ehsm_get_pub_from_priv, 从私钥计算公钥命令。 */
typedef struct {
    uint16_t cmd_id;       /* [offset: 0] 0x0805 */
    uint16_t cmd_id_inv;   /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];  /* [offset: 4] reserved */
    uint8_t reserved1[8];  /* [offset: 12] reserved */
    uint32_t key_handle;   /* [offset: 20] 私钥的句柄。 */
    uint8_t reserved2[12]; /* [offset: 24] reserved */
    raddr_t
        dh_common_addr;      /* [offset: 36] DH公共数据的地址。其数据格式为{p_len + p_value + q_len + q_value + g_len +
                                g_value + h_len +
                                h_value}。x_len的值表示x_value的长度。h_value是可选的，将h_len的值设置为0表示h_value不存在。x_len的长度为4字节。仅对生成DH密钥有效。
                              */
    uint32_t dh_common_size; /* [offset: 44] DH参数p/q/g数据的长度。仅对生成DH密钥有效。最大长度为2064字节。 */
    raddr_t public_key_addr; /* [offset: 48] 存储公钥数据的host地址。 */
    uint32_t public_key_buffer_size; /* [offset: 56] 公钥数据的缓冲区长度 */
} mb_cmd_ehsm_get_pub_from_priv_st;

/* response struct */
typedef struct {
    uint32_t ret_code;        /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t algo_id;         /* [offset: 4] 返回的公钥算法ID。 */
    uint32_t public_key_size; /* [offset: 8] 返回的公钥实际大小。 */
} mb_rsp_ehsm_get_pub_from_priv_st;

/* ---- command ehsm_get_pub_from_priv end ---- */

/* ---- command ehsm_she_load_key_cmd start ---- */

#define MB_CMD_ID_EHSM_SHE_LOAD_KEY_CMD 0x0808U /* Command ID for ehsm_she_load_key_cmd*/

/* struct ehsm_she_load_key_cmd, SHE协议加载密钥命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0808 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t m1;           /* [offset: 12] SHE密钥m1值的host地址，16字节，输入。 */
    raddr_t m2;           /* [offset: 20] SHE密钥m2值的host地址，32字节，输入。 */
    raddr_t m3;           /* [offset: 28] SHE密钥m3值的host地址，16字节，输入。 */
    raddr_t m4;           /* [offset: 36] SHE密钥m4值的host地址，32字节，输入。 */
    raddr_t m5;           /* [offset: 44] SHE密钥m5值的host地址，16字节，输入。 */
    uint8_t she_ext_flag; /* [offset: 52] 1:加载扩展SHE密钥，0:加载标准SHE密钥。 */
} mb_cmd_ehsm_she_load_key_cmd_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_ehsm_she_load_key_cmd_st;

/* ---- command ehsm_she_load_key_cmd end ---- */

/* ---- command ehsm_she_load_plain_key_cmd start ---- */

#define MB_CMD_ID_EHSM_SHE_LOAD_PLAIN_KEY_CMD 0x0809U /* Command ID for ehsm_she_load_plain_key_cmd*/

/* struct ehsm_she_load_plain_key_cmd, SHE协议加载明文密钥命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0809 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t key_data;     /* [offset: 12] 密钥明文的host地址，输入。 */
} mb_cmd_ehsm_she_load_plain_key_cmd_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_ehsm_she_load_plain_key_cmd_st;

/* ---- command ehsm_she_load_plain_key_cmd end ---- */

/* ---- command ehsm_she_ram_key_export_cmd start ---- */

#define MB_CMD_ID_EHSM_SHE_RAM_KEY_EXPORT_CMD 0x080aU /* Command ID for ehsm_she_ram_key_export_cmd*/

/* struct ehsm_she_ram_key_export_cmd, SHE协议导出密钥命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x080a */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    raddr_t m1;           /* [offset: 12] SHE密钥m1值的host地址，16字节，输入。 */
    raddr_t m2;           /* [offset: 20] SHE密钥m2值的host地址，32字节，输入。 */
    raddr_t m3;           /* [offset: 28] SHE密钥m3值的host地址，16字节，输入。 */
    raddr_t m4;           /* [offset: 36] SHE密钥m4值的host地址，32字节，输入。 */
    raddr_t m5;           /* [offset: 44] SHE密钥m5值的host地址，16字节，输入。 */
    uint8_t she_ext_flag; /* [offset: 52] 1:加载扩展SHE密钥，0:加载标准SHE密钥。 */
} mb_cmd_ehsm_she_ram_key_export_cmd_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_ehsm_she_ram_key_export_cmd_st;

/* ---- command ehsm_she_ram_key_export_cmd end ---- */

/* ---- command ehsm_she_export_total_nvm_keys start ---- */

#define MB_CMD_ID_EHSM_SHE_EXPORT_TOTAL_NVM_KEYS 0x0820U /* Command ID for ehsm_she_export_total_nvm_keys*/

/* struct ehsm_she_export_total_nvm_keys, 导出SHE密钥存储区命令。 */
typedef struct {
    uint16_t cmd_id;                  /* [offset: 0] 0x0820 */
    uint16_t cmd_id_inv;              /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];             /* [offset: 4] reserved */
    raddr_t key_data_addr;            /* [offset: 12] 存储导出的SHE NVM密钥数据的host地址。 */
    uint32_t key_data_buff_size;      /* [offset: 20] 存储导出密钥数据的缓冲区长度 */
    raddr_t key_signature_addr;       /* [offset: 24] 存储导出密钥签名数据的host地址。 */
    uint32_t key_signature_buff_size; /* [offset: 32] 存储导出密钥签名数据的缓冲区长度。 */
} mb_cmd_ehsm_she_export_total_nvm_keys_st;

/* response struct */
typedef struct {
    uint32_t ret_code;           /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_data_size;      /* [offset: 4] 返回的导出密钥数据的实际长度 */
    uint32_t key_signature_size; /* [offset: 8] 返回的导出密钥签名数据的实际长度。 */
} mb_rsp_ehsm_she_export_total_nvm_keys_st;

/* ---- command ehsm_she_export_total_nvm_keys end ---- */

/* ---- command ehsm_she_import_total_nvm_keys start ---- */

#define MB_CMD_ID_EHSM_SHE_IMPORT_TOTAL_NVM_KEYS 0x0821U /* Command ID for ehsm_she_import_total_nvm_keys*/

/* struct ehsm_she_import_total_nvm_keys, 导入SHE密钥存储区命令。 */
typedef struct {
    uint16_t cmd_id;             /* [offset: 0] 0x0821 */
    uint16_t cmd_id_inv;         /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];        /* [offset: 4] reserved */
    raddr_t key_data_addr;       /* [offset: 12] 存储导入的SHE NVM密钥数据的host地址。 */
    uint32_t key_data_size;      /* [offset: 20] 导入密钥数据的长度 */
    raddr_t key_signature_addr;  /* [offset: 24] 存储导入密钥签名数据的host地址。 */
    uint32_t key_signature_size; /* [offset: 32] 导入密钥签名数据的长度。 */
} mb_cmd_ehsm_she_import_total_nvm_keys_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_ehsm_she_import_total_nvm_keys_st;

/* ---- command ehsm_she_import_total_nvm_keys end ---- */

/* ---- command ehsm_sm9_exchg_key start ---- */

#define MB_CMD_ID_EHSM_SM9_EXCHG_KEY 0x070cU /* Command ID for ehsm_sm9_exchg_key*/

/* struct sm9_exchg_other_info_struct, SM9密钥交换其他信息的数据结构 */
typedef struct {
    raddr_t peer_tmp_pub_addr; /* [offset: 0] 对等方临时公钥的地址。 */
    raddr_t kgc_pub_key_addr;  /* [offset: 8] 密钥生成中心（KGC）的系统加密主公钥的地址，公钥大小为64字节。 */
    raddr_t fp12g_addr;        /* [offset: 16] e(P1, pub_key)值的地址，如果设置为NULL，将在eHSM中计算。 */
    raddr_t self_id_addr;      /* [offset: 24] 自身用户ID的地址。 */
    raddr_t peer_id_addr;      /* [offset: 32] 对等方用户ID的地址。 */
    uint32_t peer_id_size;     /* [offset: 40] 对等方用户ID的字节大小，最大可以为1024。 */
    uint32_t self_id_size;     /* [offset: 44] 自身ID的字节大小，最大可以为1024。 */
    raddr_t s1_s2_addr;        /* [offset: 48] S1（或S2）验证值的地址，大小为32。 */
    raddr_t sa_sb_addr;        /* [offset: 56] SA（或SB）验证值的地址，大小为32。 */
} mb_sm9_exchg_other_info_struct_st;

/* struct ehsm_sm9_exchg_key, SM9密钥交换命令。 */
typedef struct {
    uint16_t cmd_id;               /* [offset: 0] 0x070c */
    uint16_t cmd_id_inv;           /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];          /* [offset: 4] reserved */
    uint8_t algo_id;               /* [offset: 12] 交换密钥的密钥算法ID，仅对称密钥算法ID有效 */
    uint8_t reserved1[6];          /* [offset: 13] reserved */
    uint8_t role;                  /* [offset: 19] 密钥交换中的角色，发起方或响应方 */
    uint32_t user_priv_key_handle; /* [offset: 20] 用户私钥的密钥句柄。 */
    uint32_t permit;               /* [offset: 24] 生成的新密钥的权限值。密钥可以有多个权限 */
    uint8_t reserved2[4];          /* [offset: 28] reserved */
    raddr_t other_info;            /* [offset: 32] SM9密钥交换的其他信息。 */
    uint32_t user_tmp_key_handle;  /* [offset: 40] SM9密钥交换的本地临时密钥。 */
    uint8_t reserved3[4];          /* [offset: 44] reserved */
    uint32_t key_size;             /* [offset: 48] 输出密钥的字节数。 */
} mb_cmd_ehsm_sm9_exchg_key_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t key_handle; /* [offset: 4] 返回的密钥句柄。 */
} mb_rsp_ehsm_sm9_exchg_key_st;

/* ---- command ehsm_sm9_exchg_key end ---- */

/* ---- group UTC时间服务 ---- */
/* 与UTC时间相关的命令。  */

/* ---- command set_utc_time start ---- */

#define MB_CMD_ID_SET_UTC_TIME 0x0003U /* Command ID for set_utc_time*/

/* struct set_utc_time, 同步UTC计时器命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0003 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint32_t utc_time;    /* [offset: 12] 要同步的UTC时间。 */
} mb_cmd_set_utc_time_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_set_utc_time_st;

/* ---- command set_utc_time end ---- */

/* ---- command get_utc_time start ---- */

#define MB_CMD_ID_GET_UTC_TIME 0x0004U /* Command ID for get_utc_time*/

/* struct get_utc_time, 获取UTC时间命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0004 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
} mb_cmd_get_utc_time_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t utc_time; /* [offset: 4] eHSM返回的UTC时间。 */
} mb_rsp_get_utc_time_st;

/* ---- command get_utc_time end ---- */

/* ---- group 计数器 ---- */
/* 计数器相关命令。  */

/* ---- command create_counter start ---- */

#define MB_CMD_ID_CREATE_COUNTER 0x0010U /* Command ID for create_counter*/

/* struct create_counter, 启用一个未使用的计数器命令。 */
typedef struct {
    uint16_t cmd_id;     /* [offset: 0] 0x0010 */
    uint16_t cmd_id_inv; /* [offset: 2] cmd_id取反 */
} mb_cmd_create_counter_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t low_value;  /* [offset: 4] 当前计数器值的低32位。 */
    uint32_t high_value; /* [offset: 8] 当前计数器值的高32位。 */
    uint32_t counter_id; /* [offset: 12] 创建的计数器的返回ID。 */
} mb_rsp_create_counter_st;

/* ---- command create_counter end ---- */

/* ---- command read_counter start ---- */

#define MB_CMD_ID_READ_COUNTER 0x0011U /* Command ID for read_counter*/

/* struct read_counter, 读取指定计数器的当前值命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0011 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint32_t counter_id;  /* [offset: 12] 要读取的计数器的ID。 */
} mb_cmd_read_counter_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t low_value;  /* [offset: 4] 当前计数器值的低32位。 */
    uint32_t high_value; /* [offset: 8] 当前计数器值的高32位。 */
} mb_rsp_read_counter_st;

/* ---- command read_counter end ---- */

/* ---- command increase_counter_value start ---- */

#define MB_CMD_ID_INCREASE_COUNTER_VALUE 0x0012U /* Command ID for increase_counter_value*/

/* struct increase_counter_value, 增加指定计数器的当前值命令。 */
typedef struct {
    uint16_t cmd_id;        /* [offset: 0] 0x0012 */
    uint16_t cmd_id_inv;    /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8];   /* [offset: 4] reserved */
    uint32_t counter_id;    /* [offset: 12] 要设置的计数器的ID。 */
    uint8_t reserved1[4];   /* [offset: 16] reserved */
    uint32_t counter_inc_h; /* [offset: 20] 要加到计数器高32位的增加值。 */
    uint32_t counter_inc_l; /* [offset: 24] 要加到计数器低32位的增加值。 */
} mb_cmd_increase_counter_value_st;

/* response struct */
typedef struct {
    uint32_t ret_code;   /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
    uint32_t low_value;  /* [offset: 4] 当前计数器值的低32位。 */
    uint32_t high_value; /* [offset: 8] 当前计数器值的高32位。 */
} mb_rsp_increase_counter_value_st;

/* ---- command increase_counter_value end ---- */

/* ---- command delete_counter start ---- */

#define MB_CMD_ID_DELETE_COUNTER 0x0013U /* Command ID for delete_counter*/

/* struct delete_counter, 禁用指定计数器命令。 */
typedef struct {
    uint16_t cmd_id;      /* [offset: 0] 0x0013 */
    uint16_t cmd_id_inv;  /* [offset: 2] cmd_id取反 */
    uint8_t reserved0[8]; /* [offset: 4] reserved */
    uint32_t counter_id;  /* [offset: 12] 要禁用的计数器的ID。 */
} mb_cmd_delete_counter_st;

/* response struct */
typedef struct {
    uint32_t ret_code; /* [offset: 0] 0x0000A55AU 表示操作成功, 其它值表示失败. */
} mb_rsp_delete_counter_st;

/* ---- command delete_counter end ---- */


#pragma pack()

#endif
