#include "types.h"
#include "common/utils.h"
#include "api.h"

/*Definition the key algorithm ID */
#define KMS_KEY_ALG_SM4 (7U)
#define KMS_KEY_ALG_SM2 (8U)

/* 定义 OTP 密钥的逻辑 ID */
#define KMS_KEY_TYPE_OTP (0x200000U)

#define EHSM_OTP_CHIP_ROOT_KEY_ID        (KMS_KEY_TYPE_OTP + 1U)
#define EHSM_OTP_DEVICE_ROOT_KEY_ID      (KMS_KEY_TYPE_OTP + 2U)
#define EHSM_OTP_USER_ROOT_KEY_ID        (KMS_KEY_TYPE_OTP + 3U)
#define EHSM_OTP_EHSM_DEBUG_KEY_ID       (KMS_KEY_TYPE_OTP + 4U)
#define EHSM_OTP_EHSM_FW_VERIFY_KEY_ID   (KMS_KEY_TYPE_OTP + 5U)
#define EHSM_OTP_EHSM_ENCRYPT_KEY_ID     (KMS_KEY_TYPE_OTP + 6U)
#define EHSM_OTP_EHSM_UPG_ENCRYPT_KEY_ID (KMS_KEY_TYPE_OTP + 7U)
#define EHSM_OTP_EHSM_UPG_VERIFY_KEY_ID  (KMS_KEY_TYPE_OTP + 8U)
#define EHSM_OTP_EHSM_PRIVATE_KEY_ID     (KMS_KEY_TYPE_OTP + 9U)
#define EHSM_OTP_SOC_DEBUG_KEY_ID        (KMS_KEY_TYPE_OTP + 10U)
#define EHSM_OTP_SOC_FW_VERIFY_KEY_ID    (KMS_KEY_TYPE_OTP + 11U)
#define EHSM_OTP_SOC_ENCRYPT_KEY_ID      (KMS_KEY_TYPE_OTP + 12U)
#define EHSM_OTP_SOC_UPG_ENCRYPT_KEY_ID  (KMS_KEY_TYPE_OTP + 13U)
#define EHSM_OTP_SOC_UPG_VERIFY_KEY_ID   (KMS_KEY_TYPE_OTP + 14U)
#define EHSM_OTP_SOC_PRIVATE_KEY_ID      (KMS_KEY_TYPE_OTP + 15U)
#define EHSM_OTP_SECRET_KEY_KEY_ID       (KMS_KEY_TYPE_OTP + 16U)
#define EHSM_OTP_USER_AUTH_KEY_ID        (KMS_KEY_TYPE_OTP + 17U)
#define EHSM_OTP_INVALID_KEY_ID          (KMS_KEY_TYPE_OTP + 0xFFFFFU)

/* 定义密钥用途和权限 */
#define KEY_USAGE_NONE                (0x0U)
#define KEY_USAGE_SIGN                (0x1U)
#define KEY_USAGE_VERIFY              (0x2U)
#define KEY_USAGE_ENCRYPT             (0x4U)
#define KEY_USAGE_DECRYPT             (0x8U)
#define KEY_USAGE_TIMESTAMP           (0x10U)
#define KEY_USAGE_SECUREBOOT          (0x20U)
#define KEY_USAGE_SECURESTORAGE       (0x40U)
#define KEY_USAGE_KEYCREATION         (0x80U)
#define KEY_USAGE_CREATION_TRANSP_KEY (0x100U)
#define KEY_USAGE_UTCSYNC             (0x200U)
#define KEY_USAGE_TRANSPORT           (0x400U)
#define KEY_PERMIT_REMOVE             (0x800U)
#define KEY_PERMIT_IMPORT_PLAINTEXT   (0x1000U)
#define KEY_PERMIT_IMPORT_CIPHERTEXT  (0x2000U)
#define KEY_PERMIT_EXPORT_PLAINTEXT   (0x4000U)
#define KEY_PERMIT_EXPORT_CIPHERTEXT  (0x8000U)
#define KEY_PERMIT_BOOT_FAIL_USAGE    (0x10000U)
#define KEY_PERMIT_DEBUG_USAGE        (0x20000U)
#define KEY_PERMIT_WILDCARD           (0x40000U)
#define KEY_PERMIT_WR_PRT             (0x80000U)
#define KEY_USAGE_PERMIT_ALL_BITS     (0xFFFFFU)

#define KEY_USAGE_FLAGS                                                                              \
    (KEY_USAGE_SIGN | KEY_USAGE_VERIFY | KEY_USAGE_ENCRYPT | KEY_USAGE_DECRYPT | KEY_USAGE_TIMESTAMP \
        | KEY_USAGE_SECUREBOOT | KEY_USAGE_KEYCREATION | KEY_USAGE_SECURESTORAGE | KEY_USAGE_UTCSYNC)
#define KEY_EXPORT_FLAGS (KEY_PERMIT_EXPORT_PLAINTEXT | KEY_PERMIT_EXPORT_CIPHERTEXT)

/* 定义密钥生成类型 */
typedef enum { OTP_KEY_GENERATE_TYPE_DIRECT = 0, OTP_KEY_GENERATE_TYPE_DERIVE = 1 } otp_key_generate_type_e;

typedef struct {
    uint8_t key_algo_id;
    uint16_t otp_slot_id;
    uint32_t otp_logic_id;
    otp_key_generate_type_e key_gen_type;
    uint32_t key_usage;
} otp_key_attributes_st;

/* 定义 OTP 密钥映射关系，必须和固件的一致 */
static const otp_key_attributes_st g_otp_default_keyid_map[] = {
    { KMS_KEY_ALG_SM4, 0, EHSM_OTP_CHIP_ROOT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 1, EHSM_OTP_DEVICE_ROOT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 2, EHSM_OTP_USER_ROOT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_CREATION_TRANSP_KEY },
    { KMS_KEY_ALG_SM2, 3, EHSM_OTP_EHSM_DEBUG_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM2, 4, EHSM_OTP_EHSM_FW_VERIFY_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 5, EHSM_OTP_EHSM_ENCRYPT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 6, EHSM_OTP_EHSM_UPG_ENCRYPT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM2, 7, EHSM_OTP_EHSM_UPG_VERIFY_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 8, EHSM_OTP_EHSM_PRIVATE_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM2, 9, EHSM_OTP_SOC_DEBUG_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM2, 10, EHSM_OTP_SOC_FW_VERIFY_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 11, EHSM_OTP_SOC_ENCRYPT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 12, EHSM_OTP_SOC_UPG_ENCRYPT_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM2, 13, EHSM_OTP_SOC_UPG_VERIFY_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 14, EHSM_OTP_SOC_PRIVATE_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
    { KMS_KEY_ALG_SM4, 15, EHSM_OTP_SECRET_KEY_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_TRANSPORT },
    { KMS_KEY_ALG_SM4, 16, EHSM_OTP_USER_AUTH_KEY_ID, OTP_KEY_GENERATE_TYPE_DIRECT, KEY_USAGE_NONE },
};