from enum import IntFlag, IntEnum


class KeyPermit(IntFlag):
    KEY_PRIV_SIGN = 0x0001  # 密钥可用于签名或生成MAC/HMAC
    KEY_PRIV_VERIFY = 0x0002  # 密钥可用于验签或验证MAC/HMAC
    KEY_PRIV_ENCRYPT = 0x0004  # 密钥可用于加密
    KEY_PRIV_DECRYPT = 0x0008  # 密钥可用于解密
    KEY_PRIV_TIMESTAMP = 0x0010
    KEY_PRIV_SECURE_BOOT = 0x0020
    KEY_PRIV_SECURE_STORAGE = 0x0040
    KEY_PRIV_KEY_CREATION = 0x0080  # 密钥可用于派生或协商新密钥
    KEY_PRIV_TRANSPORT_KEY_CREATION = 0x0100  # 密钥可用于派生传输密钥
    KEY_PRIV_UTCSYNC = 0x0200
    KEY_PRIV_TRANSPORT = 0x0400  # 密钥可作为传输密钥使用
    KEY_PRIV_REMOVE = 0x0800  # 密钥可以被移除
    KEY_PRIV_IMPORT_PLAIN = 0x1000  # 密钥可以被明文导入
    KEY_PRIV_IMPORT_CIPHER = 0x2000  # 密钥可以被密文导入
    KEY_PRIV_EXPORT_PLAIN = 0x4000  # 密钥可以被明文导出
    KEY_PRIV_EXPORT_CIPHER = 0x8000  # 密钥可以被密文导出
    KEY_PRIV_BOOT_FAIL_USAGE = 0x10000
    KEY_PRIV_DEBUG_USAGE = 0x20000
    KEY_PRIV_WILDCARD_PROTECT = 0x40000
    KEY_PRIV_WRITE_PROTECT = 0x80000  # 密钥写保护（不能覆盖）


class EhsmChallengeType(IntEnum):
    EHSM_CHALLENGE_TYPE_EHSM_DEBUG = 1       # EHSM调试鉴权挑战，挑战值的长度为 32+16 字节
    EHSM_CHALLENGE_TYPE_SHE_DEBUG = 2        # SHE管理调试鉴权挑战，BootLoader中不支持
    EHSM_CHALLENGE_TYPE_SOC_DEBUG = 3        # SOC调试鉴权挑战，挑战值的长度为 32+16 字节
    EHSM_CHALLENGE_TYPE_USER_AUTH = 4        # FW用户行为鉴权，BootLoader中不支持，挑战值长度为 32+16 字节
    EHSM_CHALLENGE_TYPE_FW_AUTH = 5          # 国密固件认证鉴权挑战，仅BootLoader中支持，挑战值长度为 16 字节

class EhsmAuthAlgo(IntEnum):
    EHSM_AUTH_ALGO_SM3_SM2 = 1
    EHSM_AUTH_ALGO_SHA256_ECDSA_P256R1 = 2
    EHSM_AUTH_ALGO_SM4_CMAC = 3
    EHSM_AUTH_ALGO_AES128_CMAC = 4
    EHSM_AUTH_ALGO_SHA256_RSA = 5
    EHSM_AUTH_ALGO_SHA384_ECDSA_P384R1 = 6
    EHSM_AUTH_ALGO_SM4_CBC = 7

class EhsmHashAlgo(IntEnum):
    EHSM_HASH_ALGO_SM3 = 0
    EHSM_HASH_ALGO_MD5 = 1
    EHSM_HASH_ALGO_SHA256 = 2
    EHSM_HASH_ALGO_SHA384 = 3
    EHSM_HASH_ALGO_SHA512 = 4
    EHSM_HASH_ALGO_SHA1 = 5
    EHSM_HASH_ALGO_SHA224 = 6
    EHSM_HASH_ALGO_SHA512_224 = 7
    EHSM_HASH_ALGO_SHA512_256 = 8
    EHSM_HASH_ALGO_SHA3_224 = 9
    EHSM_HASH_ALGO_SHA3_256 = 10
    EHSM_HASH_ALGO_SHA3_384 = 11
    EHSM_HASH_ALGO_SHA3_512 = 12
    EHSM_HASH_ALGO_INVALID = 0xFF

class EhsmRngAlgo(IntEnum):
    EHSM_RNG_ALGO_SM4_CTR_DRBG = 0
    EHSM_RNG_ALGO_AES_CTR_DRBG = 1

class EhsmSymmAlgo(IntEnum):
    EHSM_SYMM_ALGO_DES = 0
    EHSM_SYMM_ALGO_TDES_128 = 1
    EHSM_SYMM_ALGO_TDES_192 = 2
    EHSM_SYMM_ALGO_AES_128 = 5
    EHSM_SYMM_ALGO_AES_192 = 6
    EHSM_SYMM_ALGO_AES_256 = 7
    EHSM_SYMM_ALGO_SM4 = 8
    EHSM_SYMM_ALGO_INVALID = 0xFF

class EhsmMacMode(IntEnum):
    EHSM_MAC_MODE_CMAC = 7
    EHSM_MAC_MODE_CBC_MAC = 8
    EHSM_MAC_MODE_GMAC = 9
    EHSM_MAC_MODE_INVALID = 0xFF

class EhsmPaddingMode(IntEnum):
    EHSM_PADDING_NONE = 0
    EHSM_PADDING_PKCS7 = 2                   # PKCS7，兼容PKCS5
    EHSM_PADDING_ONE_WITH_ZEROS = 3          # ISO7816-4

class EhsmRsaPaddingMode(IntEnum):
    EHSM_RSA_PADDING_NONE = 0
    EHSM_RSA_PADDING_PSS  = 1
    EHSM_RSA_PADDING_OAEP = 2 # don't support now

class EhsmCipherMode(IntEnum):
    EHSM_CIPHER_MODE_ECB = 1
    EHSM_CIPHER_MODE_XTS = 2
    EHSM_CIPHER_MODE_CBC = 3
    EHSM_CIPHER_MODE_CFB = 4
    EHSM_CIPHER_MODE_OFB = 5
    EHSM_CIPHER_MODE_CTR = 6

class EhsmAeadMode(IntEnum):
    EHSM_AEAD_MODE_GCM = 0
    EHSM_AEAD_MODE_CCM = 1

class EhsmKeyType(IntEnum):
    EHSM_KEY_TYPE_DES = 0x01
    EHSM_KEY_TYPE_TDES_128 = 0x02
    EHSM_KEY_TYPE_TDES_192 = 0x03
    EHSM_KEY_TYPE_AES_128 = 0x04
    EHSM_KEY_TYPE_AES_192 = 0x05
    EHSM_KEY_TYPE_AES_256 = 0x06
    EHSM_KEY_TYPE_SM4 = 0x07
    EHSM_KEY_TYPE_SM2 = 0x08
    EHSM_KEY_TYPE_RSA_1024 = 0x09
    EHSM_KEY_TYPE_RSA_2048 = 0x0a
    EHSM_KEY_TYPE_RSA_3072 = 0x0b
    EHSM_KEY_TYPE_RSA_4096 = 0x0c
    EHSM_KEY_TYPE_RSA_1024_CRT = 0x0d
    EHSM_KEY_TYPE_RSA_2048_CRT = 0x0e
    EHSM_KEY_TYPE_RSA_3072_CRT = 0x0f
    EHSM_KEY_TYPE_RSA_4096_CRT = 0x10
    EHSM_KEY_TYPE_DH = 0x11
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_160R1 = 0x12
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_192R1 = 0x13
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_224R1 = 0x14
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_256R1 = 0x15
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_320R1 = 0x16
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_384R1 = 0x17
    EHSM_KEY_TYPE_ECC_BRAINPOOLP_512R1 = 0x18
    EHSM_KEY_TYPE_ECC_SECP_192R1 = 0x19
    EHSM_KEY_TYPE_ECC_SECP_224R1 = 0x1a
    EHSM_KEY_TYPE_ECC_SECP_256R1 = 0x1b
    EHSM_KEY_TYPE_ECC_SECP_384R1 = 0x1c
    EHSM_KEY_TYPE_ECC_SECP_521R1 = 0x1d
    EHSM_KEY_TYPE_ED25519 = 0x1e
    EHSM_KEY_TYPE_X25519 = 0x1f
    EHSM_KEY_TYPE_SM4_XTS = 0x20
    EHSM_KEY_TYPE_AES_128_XTS = 0x21
    EHSM_KEY_TYPE_AES_192_XTS = 0x22
    EHSM_KEY_TYPE_AES_256_XTS = 0x23
    EHSM_KEY_TYPE_CHACHA = 0x24
    EHSM_KEY_TYPE_HMAC = 0x25
    EHSM_KEY_TYPE_ECC_SECP_160K1 = 0x26
    EHSM_KEY_TYPE_ECC_SECP_192K1 = 0x27
    EHSM_KEY_TYPE_ECC_SECP_224K1 = 0x28
    EHSM_KEY_TYPE_ECC_SECP_256K1 = 0x29
    EHSM_KEY_TYPE_SM9_ENC_USERPRIV = 0x2a
    EHSM_KEY_TYPE_SM9_SIGN_USERPRIV = 0x2b
    EHSM_KEY_TYPE_SM9_EXCHG_USERPRIV = 0x2c
    EHSM_KEY_TYPE_SM9_EXCHG_TEMP = 0x2d
    EHSM_KEY_TYPE_ECC_SECP_160R1 = 0x2e
    EHSM_KEY_TYPE_ECC_SECP_160R2 = 0x2f
    # PQC 密钥类型 (NIST 后量子密码标准)
    EHSM_KEY_TYPE_ML_KEM_512 = 0x30      # ML-KEM-512 (NIST安全级别1，等效AES-128)
    EHSM_KEY_TYPE_ML_KEM_768 = 0x31      # ML-KEM-768 (NIST安全级别3，等效AES-192)
    EHSM_KEY_TYPE_ML_KEM_1024 = 0x32     # ML-KEM-1024 (NIST安全级别5，等效AES-256)
    EHSM_KEY_TYPE_ML_DSA_44 = 0x33       # ML-DSA-44 (NIST安全级别2)
    EHSM_KEY_TYPE_ML_DSA_65 = 0x34       # ML-DSA-65 (NIST安全级别3)
    EHSM_KEY_TYPE_ML_DSA_87 = 0x35       # ML-DSA-87 (NIST安全级别5)
    EHSM_KEY_TYPE_SLH_DSA_SHA2_128S = 0x36    # SLH-DSA-SHA2-128s
    EHSM_KEY_TYPE_SLH_DSA_SHAKE_128S = 0x37   # SLH-DSA-SHAKE-128s
    EHSM_KEY_TYPE_SLH_DSA_SHA2_128F = 0x38    # SLH-DSA-SHA2-128f
    EHSM_KEY_TYPE_SLH_DSA_SHAKE_128F = 0x39   # SLH-DSA-SHAKE-128f
    EHSM_KEY_TYPE_SLH_DSA_SHA2_192S = 0x3A    # SLH-DSA-SHA2-192s
    EHSM_KEY_TYPE_SLH_DSA_SHAKE_192S = 0x3B   # SLH-DSA-SHAKE-192s
    EHSM_KEY_TYPE_SLH_DSA_SHA2_192F = 0x3C    # SLH-DSA-SHA2-192f
    EHSM_KEY_TYPE_SLH_DSA_SHAKE_192F = 0x3D   # SLH-DSA-SHAKE-192f
    EHSM_KEY_TYPE_SLH_DSA_SHA2_256S = 0x3E    # SLH-DSA-SHA2-256s
    EHSM_KEY_TYPE_SLH_DSA_SHAKE_256S = 0x3F   # SLH-DSA-SHAKE-256s
    EHSM_KEY_TYPE_SLH_DSA_SHA2_256F = 0x40    # SLH-DSA-SHA2-256f
    EHSM_KEY_TYPE_SLH_DSA_SHAKE_256F = 0x41   # SLH-DSA-SHAKE-256f

class EhsmKeyPart(IntEnum):
    EHSM_KEY_PART_PUBLIC_KEY = 1             # 密钥数据结构体中仅包含公钥
    EHSM_KEY_PART_PRIVATE_KEY = 2            # 密钥数据结构体中仅包含私钥
    EHSM_KEY_PART_SYMM_KEY = 2               # 密钥数据结构体包含的是对称密钥
    EHSM_KEY_PART_KEY_PAIR = 3               # 密钥数据结构体包含的是密钥对

class EhsmDeriveAlgo(IntEnum):
    EHSM_DERIVE_ALGO_KDFX963 = 1
    EHSM_DERIVE_ALGO_PBKDF2 = 2

class EhsmDeriveType(IntEnum):
    EHSM_DERIVE_TYPE_PASSWORD = 1            # 使用password派生
    EHSM_DERIVE_TYPE_FROM_PARENT_KEY = 2     # 从父密钥派生

class EhsmSm2Role(IntEnum):
    EHSM_SM2_ROLE_SPONSOR = 0
    EHSM_SM2_ROLE_RESPONSOR = 1

class EhsmSm9EncType(IntEnum):
    EHSM_SM9_ENC_TYPE_STREAM = 0
    EHSM_SM9_ENC_TYPE_BLOCK = 1

class EhsmSm9PaddingMode(IntEnum):
    EHSM_SM9_PADDING_NONE = 0
    EHSM_SM9_PADDING_PKCS7 = 1

class EhsmSm9Role(IntEnum):
    EHSM_SM9_ROLE_SPONSOR = 0
    EHSM_SM9_ROLE_RESPONSOR = 1

class EhsmDrvMode(IntEnum):
    EHSM_DRV_MODE_INTERRUPT = 0              # 中断模式
    EHSM_DRV_MODE_WAIT_AND_POLL = 1          # 同步等待模式
    EHSM_DRV_MODE_SEND_AND_PEEK = 2          # 发送并由用户POLL

class EhsmKeyLevel(IntEnum):
    EHSM_KEY_LEVEL_1 = 1                     # 此OTP密钥由CHIP ROOT KEY加密，仅支持 TEST_MODE 和 DEVVELOP_MODE
    EHSM_KEY_LEVEL_2 = 2                     # 此OTP密钥由DEVICE ROOT KEY加密，仅支持 TEST_MODE 、DEVELOP_MODE 和 MANUFACTURE_MODE

class EhsmInstallKeyType(IntEnum):
    EHSM_INSTALL_KEY_TYPE_SYMM = 1
    EHSM_INSTALL_KEY_TYPE_ASYM_PRIV_KEY = 2
    EHSM_INSTALL_KEY_TYPE_ASYM_PUB_KEY_HASH = 4

class EhsmBlGenKeyType(IntEnum):
    EHSM_BL_GEN_KEY_TYPE_SYMM = 1
    EHSM_BL_GEN_KEY_TYPE_SM2 = 2
    EHSM_BL_GEN_KEY_TYPE_ECC_P256R1 = 4

class EhsmCtrlField(IntEnum):
    EHSM_CTRL_FIELD_HW = 0
    EHSM_CTRL_FIELD_EHSM = 1
    EHSM_CTRL_FIELD_SOC = 2

class EhsmLifecycle(IntEnum):
    EHSM_LC_TEST  = 1
    EHSM_LC_DEVELOP  = 2
    EHSM_LC_MANUFACTURE = 3
    EHSM_LC_USER = 4
    EHSM_LC_DEBUG = 5
    EHSM_LC_DESTORY = 6

class EhsmPqcSignMode(IntEnum):
    EHSM_PQC_PURE_DSA_WITH_MSG = 0       # 由 Host 输入消息，HSM 使用 Pure DSA 接口签名验签
    EHSM_PQC_PRE_HASH_DSA_WITH_DIGEST = 1  # 由 Host 输入消息摘要，HSM 使用 Pre-Hash DSA 接口签名验签

class EhsmPqcSignAlgo(IntEnum):
    EHSM_PQC_DSA_ALGO_ML_DSA = 0   # ML-DSA - 基于格的模块化DSA算法(FIPS 204)
    EHSM_PQC_DSA_ALGO_SLH_DSA = 1  # SLH-DSA - 基于哈希的无状态层次化DSA算法(FIPS 205)

class EhsmPqcHashAlgo(IntEnum):
    EHSM_PQC_HASH_ALGO_SHA256 = 2        # SHA-256 哈希算法
    EHSM_PQC_HASH_ALGO_SHA384 = 3        # SHA-384 哈希算法
    EHSM_PQC_HASH_ALGO_SHA512 = 4        # SHA-512 哈希算法
    EHSM_PQC_HASH_ALGO_SHA1 = 5          # SHA-1 哈希算法（不建议使用）
    EHSM_PQC_HASH_ALGO_SHA224 = 6        # SHA-224 哈希算法
    EHSM_PQC_HASH_ALGO_SHA512_224 = 7    # SHA-512/224 哈希算法
    EHSM_PQC_HASH_ALGO_SHA512_256 = 8    # SHA-512/256 哈希算法
    EHSM_PQC_HASH_ALGO_SHA3_224 = 9      # SHA3-224 哈希算法
    EHSM_PQC_HASH_ALGO_SHA3_256 = 10     # SHA3-256 哈希算法
    EHSM_PQC_HASH_ALGO_SHA3_384 = 11     # SHA3-384 哈希算法
    EHSM_PQC_HASH_ALGO_SHA3_512 = 12     # SHA3-512 哈希算法
    EHSM_PQC_HASH_ALGO_SHAKE128 = 13     # SHAKE128 哈希算法
    EHSM_PQC_HASH_ALGO_SHAKE256 = 14     # SHAKE256 哈希算法

class EhsmPqcOutType(IntEnum):
    EHSM_PQC_OUT_KEY_HANDLE = 0  # 输出为密钥句柄，密钥保存在eHSM内部
    EHSM_PQC_OUT_PLAIN_KEY = 1   # 输出为明文密钥，直接返回密钥内容