//========================================================================================
// Copyright (C) 2026 Open Security Research Inc. - All Rights Reserved
// 
// Version: v1.1.0-a
// 
// 4019 4_1_0_dev_Intellifusion ac64bbf3e97113d575f8d196a8a63253d369e0a9
// 5990b6d6faa02bb3276acdc07eac001c11d17ec3
//========================================================================================

module osr_wing_m130a_top_wrapper (
input   logic                always_on_clk , 
input   logic                clk , 
output  logic                clk_gate_en , 
input   logic                pwrup_rst_n , 
input   logic                ndm_rst_n , 
output  logic                dm_ndmreset , 
input   logic                soft_rst_n , 
output  logic                soft_rst_req , 
output  logic                core_sleeping , 
output  logic                core_deep_sleeping , 
input   logic   [32-1:0]     boot_pc , 
input   logic   [32-1:0]     hart_id , 
input   logic                ref_clk , 
input   logic   [32-1:0]     core_mmr_base_addr , 
input   logic   [15:0]       reri_bank_inst_id , 
input   logic                core_wait , 
input   logic                endianess , 
output  logic                halted , 
output  logic                lockup , 
input   logic   [32+1:0]     timer_calibration , 
input   logic                trst_n , 
input   logic                tck , 
input   logic                tms , 
input   logic                tdi , 
output  logic                tdo , 
output  logic                tdo_en , 
input   logic                ext_interrupt , 
input   logic   [64-1:0]     loc_interrupt ,

output  logic   [31:0]       i_haddr , 
output  logic   [2:0]        i_hburst , 
output  logic   [3:0]        i_hprot , 
output  logic   [2:0]        i_hsize , 
output  logic   [1:0]        i_htrans , 
output  logic                i_hwrite , 
output  logic   [31:0]       i_hwdata , 
input   logic   [31:0]       i_hrdata , 
input   logic                i_hready , 
input   logic                i_hresp , 
output  logic   [1:0]        i_hmaster , 

output  logic   [31:0]       d_haddr , 
output  logic   [2:0]        d_hburst , 
output  logic   [3:0]        d_hprot , 
output  logic   [2:0]        d_hsize , 
output  logic   [1:0]        d_htrans , 
output  logic                d_hwrite , 
output  logic   [31:0]       d_hwdata , 
input   logic   [31:0]       d_hrdata , 
input   logic                d_hready , 
input   logic                d_hresp , 
output  logic   [1:0]        d_hmaster , 

output  logic   [31:0]       m_haddr , 
output  logic   [2:0]        m_hburst , 
output  logic   [3:0]        m_hprot , 
output  logic   [2:0]        m_hsize , 
output  logic   [1:0]        m_htrans , 
output  logic                m_hwrite , 
output  logic   [31:0]       m_hwdata , 
input   logic   [31:0]       m_hrdata , 
input   logic                m_hready , 
input   logic                m_hresp , 
output  logic   [1:0]        m_hmaster , 

input   logic                dbg_authen , 
output  logic   [15:0]       err_bus , 
input   logic                dft_icg_scan_en , 
input   logic                dft_scan_mode , 
input   logic                dft_scan_rst_n 
);

wing_m130_top u_wing_m130a_top (
    .always_on_clk                         ( always_on_clk           ), 
    .clk                                   ( clk                     ), 
    .clk_gate_en                           ( clk_gate_en             ), 
    .pwrup_rst_n                           ( pwrup_rst_n             ), 
    .ndm_rst_n                             ( ndm_rst_n               ), 
    .dm_ndmreset                           ( dm_ndmreset             ), 
    .soft_rst_n                            ( soft_rst_n              ), 
    .soft_rst_req                          ( soft_rst_req            ), 
    .core_sleeping                         ( core_sleeping           ), 
    .core_deep_sleeping                    ( core_deep_sleeping      ), 
    .boot_pc                               ( boot_pc                 ), 
    .hart_id                               ( hart_id                 ), 
    .ref_clk                               ( ref_clk                 ), 
    .core_mmr_base_addr                    ( core_mmr_base_addr      ), 
    .reri_bank_inst_id                     ( reri_bank_inst_id       ), 
    .core_wait                             ( core_wait               ), 
    .endianess                             ( endianess               ), 
    .halted                                ( halted                  ), 
    .lockup                                ( lockup                  ), 
    .timer_calibration                     ( timer_calibration       ), 
    .trst_n                                ( trst_n                  ), 
    .tck                                   ( tck                     ), 
    .tms                                   ( tms                     ), 
    .tdi                                   ( tdi                     ), 
    .tdo                                   ( tdo                     ), 
    .tdo_en                                ( tdo_en                  ), 
    .ext_interrupt                         ( ext_interrupt           ), 
    .loc_interrupt                         ( loc_interrupt           ), 
    .i_haddr                               ( i_haddr                 ), 
    .i_hburst                              ( i_hburst                ), 
    .i_hprot                               ( i_hprot                 ), 
    .i_hsize                               ( i_hsize                 ), 
    .i_htrans                              ( i_htrans                ), 
    .i_hwrite                              ( i_hwrite                ), 
    .i_hwdata                              ( i_hwdata                ), 
    .i_hrdata                              ( i_hrdata                ), 
    .i_hready                              ( i_hready                ), 
    .i_hresp                               ( i_hresp                 ), 
    .i_hmaster                             ( i_hmaster               ), 
    .d_haddr                               ( d_haddr                 ), 
    .d_hburst                              ( d_hburst                ), 
    .d_hprot                               ( d_hprot                 ), 
    .d_hsize                               ( d_hsize                 ), 
    .d_htrans                              ( d_htrans                ), 
    .d_hwrite                              ( d_hwrite                ), 
    .d_hwdata                              ( d_hwdata                ), 
    .d_hrdata                              ( d_hrdata                ), 
    .d_hready                              ( d_hready                ), 
    .d_hresp                               ( d_hresp                 ), 
    .d_hmaster                             ( d_hmaster               ), 
    .m_haddr                               ( m_haddr                 ), 
    .m_hburst                              ( m_hburst                ), 
    .m_hprot                               ( m_hprot                 ), 
    .m_hsize                               ( m_hsize                 ), 
    .m_htrans                              ( m_htrans                ), 
    .m_hwrite                              ( m_hwrite                ), 
    .m_hwdata                              ( m_hwdata                ), 
    .m_hrdata                              ( m_hrdata                ), 
    .m_hready                              ( m_hready                ), 
    .m_hresp                               ( m_hresp                 ), 
    .m_hmaster                             ( m_hmaster               ), 
    .dbg_authen                            ( dbg_authen              ), 
    .err_bus                               ( err_bus                 ), 
    .dft_icg_scan_en                       ( dft_icg_scan_en         ), 
    .dft_scan_mode                         ( dft_scan_mode           ), 
    .dft_scan_rst_n                        ( dft_scan_rst_n          )  
    ); 

endmodule 
