//========================================================================================
// Copyright (C) 2026 Open Security Research Inc. - All Rights Reserved
// 
// Version: v1.1.0-a
// 
// 4019 4_1_0_dev_Intellifusion ac64bbf3e97113d575f8d196a8a63253d369e0a9
// 5990b6d6faa02bb3276acdc07eac001c11d17ec3
//========================================================================================

module osr_hash_wrapper (
    input   wire                     i_clk_core                     ,
    input   wire                     i_rst_n_core                   ,
    input   wire                     i_clk_ahb                      ,
    input   wire                     i_rst_n_ahb                    ,
    input   wire                     i_clk_axi                      ,
    input   wire                     i_rst_n_axi                    ,
    input   wire                     i_s_hsel                       ,
    input   wire   [11:0]            i_s_haddr                      ,
    input   wire   [1:0]             i_s_htrans                     ,
    input   wire                     i_s_hwrite                     ,
    input   wire   [2:0]             i_s_hburst                     ,
    input   wire   [2:0]             i_s_hsize                      ,
    input   wire   [3:0]             i_s_hprot                      ,
    input   wire                     i_s_hmastlock                  ,
    input   wire                     i_s_hready                     ,
    input   wire   [31:0]            i_s_hwdata                     ,
    output  wire   [31:0]            o_s_hrdata                     ,
    output  wire                     o_s_hresp                      ,
    output  wire                     o_s_hreadyout                  ,
    output  wire                     o_dma_done_clr                 ,
    output  wire   [64-1:0]            o_dma_saddr         ,
    output  wire   [64-1:0]            o_dma_daddr         ,
    output  wire   [31:0]            o_dma_rlen                     ,
    output  wire   [31:0]            o_dma_wlen                     ,
    output  wire                     o_dma_rstart                   ,
    output  wire                     o_dma_suspend                  ,
    output  wire                     o_dma_wstart                   ,
    input   wire                     i_dma_suspend_done             ,
    input   wire                     i_dma_rdone                    ,
    input   wire                     i_dma_wdone                    ,
    output  wire   [4:0] o_dma_r_fifo_num_count     ,
    output  wire                     o_dma_r_fifo_full              ,
    input   wire                     i_dma_r_fifo_wr                ,
    input   wire   [64-1:0] i_dma_r_fifo_wr_data           ,
    output  wire   [4:0] o_dma_w_fifo_num_count     ,
    output  wire                     o_dma_w_fifo_empty             ,
    input   wire                     i_dma_w_fifo_rd                ,
    output  wire   [64-1:0] o_dma_w_fifo_rd_data           ,
    output  wire                     o_irq                          ,
    input   wire                     i_ahb_endian                   ,
    input   wire   [255:0]           i_sp_data                      ,
    input   wire                     i_sp_valid              
);

osr_hash_hp_top #(
    .p_HMAC_EN                 (1      ),
    .p_MD5_EN                  (1       ),
    .p_SHA1_EN                 (1      ),
    .p_SHA256_EN               (1    ),    
    .p_SHA512_EN               (1    ),    
    .p_SHA3_EN                 (1      ),
    .p_SM3_EN                  (1       ),
    .p_DMA_ADDR_WIDTH          (64               ),
    .p_DMA_DATA_WIDTH          (64               ),
    .p_DMA_FIFO_DP_WIDTH       (4         ),
    .p_DMA_BYTE_GRANULARITY    (16'h20   )
) u_hash_hp_top (
    .clk_core                  ( i_clk_core             ), 
    .rst_n_core                ( i_rst_n_core           ), 
    .clk_ahb                   ( i_clk_ahb              ), 
    .rst_n_ahb                 ( i_rst_n_ahb            ), 
    .clk_axi                   ( i_clk_axi              ), 
    .rst_n_axi                 ( i_rst_n_axi            ), 
    .i_s_hsel                  ( i_s_hsel               ), 
    .i_s_haddr                 ( i_s_haddr              ), 
    .i_s_hwrite                ( i_s_hwrite             ), 
    .i_s_hsize                 ( i_s_hsize              ), 
    .i_s_hburst                ( i_s_hburst             ), 
    .i_s_hprot                 ( i_s_hprot              ), 
    .i_s_htrans                ( i_s_htrans             ), 
    .i_s_hmastlock             ( i_s_hmastlock          ), 
    .i_s_hready                ( i_s_hready             ), 
    .i_s_hwdata                ( i_s_hwdata             ), 
    .o_s_hreadyout             ( o_s_hreadyout          ), 
    .o_s_hresp                 ( o_s_hresp              ), 
    .o_s_hrdata                ( o_s_hrdata             ), 
    .o_dma_saddr               ( o_dma_saddr            ), 
    .o_dma_daddr               ( o_dma_daddr            ), 
    .o_dma_rlen                ( o_dma_rlen             ), 
    .o_dma_wlen                ( o_dma_wlen             ), 
    .o_dma_rstart              ( o_dma_rstart           ), 
    .o_dma_wstart              ( o_dma_wstart           ), 
    .o_dma_suspend             ( o_dma_suspend          ), 
    .i_dma_suspend_done        ( i_dma_suspend_done     ), 
    .i_dma_rdone               ( i_dma_rdone            ), 
    .i_dma_wdone               ( i_dma_wdone            ), 
    .o_dma_r_fifo_num_count    ( o_dma_r_fifo_num_count ), 
    .o_dma_r_fifo_full         ( o_dma_r_fifo_full      ), 
    .i_dma_r_fifo_wr           ( i_dma_r_fifo_wr        ), 
    .i_dma_r_fifo_wr_data      ( i_dma_r_fifo_wr_data   ), 
    .o_dma_w_fifo_num_count    ( o_dma_w_fifo_num_count ), 
    .o_dma_w_fifo_empty        ( o_dma_w_fifo_empty     ), 
    .i_dma_w_fifo_rd           ( i_dma_w_fifo_rd        ), 
    .o_dma_w_fifo_rd_data      ( o_dma_w_fifo_rd_data   ), 
    .o_irq                     ( o_irq                  ), 
    .i_ahb_endian              ( i_ahb_endian           ), 
    .i_sp_data                 ( i_sp_data              ), 
    .i_sp_valid                ( i_sp_valid             )  
    ); 
    assign o_dma_done_clr = 1'b0;
endmodule 
