/* eHSM Image Tool - C FFI Interface */

#ifndef EHSM_IMGTOOL_CLIB_H
#define EHSM_IMGTOOL_CLIB_H

/* Generated with cbindgen:0.29.2 */

/* warning: this file is generated by cbindgen, do not change the content! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C FFI error codes
 */
typedef enum EhsmErrorCode {
  Success = 0,
  NullPointer = 1,
  InvalidUtf8 = 2,
  ConfigError = 3,
  GenerationError = 4,
  BufferTooSmall = 5,
} EhsmErrorCode;

/**
 * Generate image and export as C array source file
 *
 * # Parameters
 * - config_path: configuration file path (C string, must be null-terminated)
 * - c_output_path: output .c file path (C string, must be null-terminated)
 * - var_name: optional C array variable name (can be NULL, auto-derived from path)
 * - err_msg_buf: error message buffer (can be NULL)
 * - err_msg_len: error message buffer size
 *
 * # Return value
 * - EhsmErrorCode enum value
 *
 * # Safety
 * - config_path and c_output_path must be valid null-terminated C string pointers
 * - var_name can be NULL or a valid null-terminated C string pointer
 * - If err_msg_buf is not NULL, it must point to at least err_msg_len bytes of valid memory
 * - All non-NULL pointers must remain valid for the duration of the function call
 */
enum EhsmErrorCode gen_image_c_array_from_config(const char *config_path,
                                                 const char *c_output_path,
                                                 const char *var_name,
                                                 char *err_msg_buf,
                                                 uint32_t err_msg_len);

/**
 * Generate image from configuration file
 *
 * # Parameters
 * - config_path: configuration file path (C string, must be null-terminated)
 * - output_buf: output buffer (allocated by caller)
 * - output_len: [in/out] input is buffer size, output is actual bytes written
 * - err_msg_buf: error message buffer (can be NULL)
 * - err_msg_len: error message buffer size
 *
 * # Return value
 * - EhsmErrorCode enum value
 *
 * # Safety
 * - config_path must be a valid null-terminated C string pointer
 * - output_buf must point to at least output_len bytes of valid memory
 * - output_len must be a valid pointer pointing to correct buffer size
 * - If err_msg_buf is not NULL, it must point to at least err_msg_len bytes of valid memory
 * - All pointers must remain valid for the duration of the function call
 */
enum EhsmErrorCode gen_image_from_config(const char *config_path,
                                         uint8_t *output_buf,
                                         uint32_t *output_len,
                                         char *err_msg_buf,
                                         uint32_t err_msg_len);

/**
 * Get output image size from configuration file (without actually generating image)
 *
 * # Parameters
 * - config_path: configuration file path (C string)
 * - image_size: [out] output image size
 * - err_msg_buf: error message buffer (can be NULL)
 * - err_msg_len: error message buffer size
 *
 * # Return value
 * - EhsmErrorCode enum value
 *
 * # Purpose
 * Allows caller to query required buffer size in advance, then allocate sufficient memory
 *
 * # Safety
 * - config_path must be a valid null-terminated C string pointer
 * - image_size must be a valid pointer
 * - If err_msg_buf is not NULL, it must point to at least err_msg_len bytes of valid memory
 * - All pointers must remain valid for the duration of the function call
 */
enum EhsmErrorCode get_image_size_from_config(const char *config_path,
                                              uint32_t *image_size,
                                              char *err_msg_buf,
                                              uint32_t err_msg_len);

/**
 * Get library version information
 *
 * # Return value
 * - Pointer to version string (static lifetime, no need to free)
 */
const char *get_imgtool_lib_version(void);

#endif  /* EHSM_IMGTOOL_CLIB_H */
