#ifndef TYPES_H
#define TYPES_H

#define EHSM_ERR_SW_SUCCESS     (0xA55A5AA5U)
#define EHSM_ERR_PARAM_ERROR    (1U)
#define EHSM_ERR_INIT_DEV_FAIL  (15U)
#define EHSM_ERR_WRITE_DEV_FAIL (16U)
#define EHSM_ERR_READ_DEV_FAIL  (17U)
#define EHSM_ERR_ERASE_DEV_FAIL (18U)

#endif // TYEPS_H
